import { ChangeEvent, useState } from "react";
import { applySkiAreaCatalog, getSkiAreaCatalogImport, previewSkiAreaCatalog } from "@/lib/adminSkiAreaCatalogApi";
import type { CatalogImport, CatalogPreview } from "@/types/skiAreaCatalog";

const countLabels: Record<string,string> = { areas_new:"Nouveaux domaines (brouillons)",areas_mapped:"Domaines déjà présents",area_collisions:"Collisions de domaines",stations_matched:"Stations existantes",stations_inactive:"Stations existantes inactives",stations_missing:"Stations manquantes",stations_optional_detail:"Détails facultatifs déjà couverts",stations_candidates:"Correspondances à vérifier",conflicts:"Conflits",memberships_linkable:"Rattachements à ajouter",memberships_pending:"Rattachements en attente" };
const stationLabels = { matched:"Existante",missing:"Manquante",candidate:"À vérifier",optional_detail:"Détail facultatif",conflict:"Conflit" };

export default function CatalogImportPanel() {
  const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<CatalogPreview|null>(null),[report,setReport]=useState<CatalogImport|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState("");
  const choose=(event:ChangeEvent<HTMLInputElement>)=>{setFile(event.target.files?.[0]||null);setPreview(null);setReport(null);setError("");};
  const run=async()=>{if(!file)return;setBusy(true);setError("");try{if(file.name!=="snow_explorer_domaines_import.json")throw new Error("Sélectionnez le fichier snow_explorer_domaines_import.json.");if(file.size>2*1024*1024)throw new Error("Le fichier dépasse la limite de 2 Mio.");setPreview(await previewSkiAreaCatalog());}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const apply=async()=>{if(!preview)return;setBusy(true);setError("");try{const result=await applySkiAreaCatalog(preview.sha256);setReport(await getSkiAreaCatalogImport(result.id));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="catalog-stack">
    <section className="catalog-panel"><h2>Fichier du catalogue</h2><p>Choisissez la copie locale pour confirmer le lot. Pour des raisons de sécurité, elle n’est pas téléversée : l’API prévisualise sa copie canonique et renvoie les statistiques de la base actuelle.</p><div className="catalog-file"><label className="btn btn--secondary">Sélectionner le fichier JSON<input aria-label="Fichier JSON du catalogue" type="file" accept="application/json,.json" onChange={choose}/></label><span>{file?.name||"Aucun fichier sélectionné"}</span><button className="btn btn--primary" disabled={!file||busy} onClick={()=>void run()}>{busy?"Analyse…":"Prévisualiser l’import"}</button></div></section>
    {error&&<div className="admin-form-error" role="alert"><strong>Import impossible.</strong><br/>{error}</div>}
    {preview&&<><section className="catalog-panel"><div className="catalog-title"><div><h2>Prévisualisation</h2><p>Lot {preview.batch_id} · {(preview.size_bytes/1024).toFixed(1)} Kio · {preview.non_exhaustive?"catalogue non exhaustif":"catalogue exhaustif"}</p></div><code>{preview.sha256.slice(0,16)}…</code></div><div className="catalog-counts">{Object.entries(countLabels).map(([key,label])=><div key={key}><strong>{preview.counts[key]??0}</strong><span>{label}</span></div>)}</div><p className="catalog-callout">Les relations du fichier ne sont pas toutes de nouveaux liens : les rattachements en attente, les détails facultatifs et les relations déjà présentes restent distingués.</p></section>
    <section className="catalog-panel"><h2>Domaines et correspondances</h2><div className="catalog-split"><div><h3>Domaines</h3><ul className="catalog-list">{preview.areas.map(a=><li key={a.catalog_key}><strong>{a.name}</strong><span>{a.state==="new"?"Nouveau brouillon":a.state==="mapped"?"Déjà présent":"Collision — aucune fusion automatique"}</span></li>)}</ul></div><div><h3>Stations</h3><ul className="catalog-list">{preview.stations.map(s=><li key={s.station_ref}><strong>{s.name}</strong><span>{stationLabels[s.state]}{s.state==="matched"&&s.is_active===false?" · inactive":""}</span></li>)}</ul></div></div></section>
    {(preview.review_proposals.length>0||preview.alerts.length>0)&&<section className="catalog-panel"><h2>Vérifications, exclusions et alertes</h2><pre className="catalog-json">{JSON.stringify({review_proposals:preview.review_proposals,alerts:preview.alerts},null,2)}</pre></section>}
    <section className="catalog-panel catalog-apply"><div><h2>Appliquer ce lot</h2><p>Les nouveaux domaines seront créés en brouillon. Aucune station ne sera créée ou activée.</p></div><button className="btn btn--primary" disabled={busy} onClick={()=>void apply()}>{busy?"Application…":"Appliquer l’import"}</button></section></>}
    {report&&<section className="catalog-panel"><h2>Bilan réel de l’import</h2><p className="admin-form-success" role="status">Import {report.status} le {new Date(report.applied_at).toLocaleString("fr-FR")}.</p><div className="catalog-counts">{Object.entries(report.result).filter(([,v])=>typeof v==="number").map(([k,v])=><div key={k}><strong>{String(v)}</strong><span>{k.replaceAll("_"," ")}</span></div>)}</div>{Array.isArray(report.result.conflicts)&&report.result.conflicts.length>0&&<pre className="catalog-json">{JSON.stringify(report.result.conflicts,null,2)}</pre>}</section>}
  </div>;
}
