import { useRouter } from "next/router";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import StationSearch from "./StationSearch";
import { newsletterApi, NewsletterApiError } from "@/lib/api/newsletter";
import { newsletterLanguage, translator } from "@/lib/newsletter/i18n";
import type { NewsletterPreferencesData, SnowAlert, StationPreference, StationSummary } from "@/types/newsletter";

const preferenceKeys = ["snow_conditions", "snowfall", "weather", "resort_updates", "opening_closing", "lift_updates", "ski_pass_updates", "articles"] as const;
const stationValue = (item: StationPreference): StationSummary => item.station || item;
const replaceById = <T extends { id: string | number }>(items: T[], value: T) => items.map((item) => String(item.id) === String(value.id) ? value : item);

export default function NewsletterPreferences({ token }: { token: string }) {
  const router = useRouter(); const t = translator(newsletterLanguage(router));
  const [data, setData] = useState<NewsletterPreferencesData | null>(null); const [draftPrefs, setDraftPrefs] = useState<Record<string, boolean>>({}); const [frequency, setFrequency] = useState("weekly");
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [adding, setAdding] = useState(false); const [confirmUnsubscribe, setConfirmUnsubscribe] = useState(false); const [unsubscribed, setUnsubscribed] = useState(false);
  const fail = useCallback((e: unknown) => { const apiError = e instanceof NewsletterApiError ? e : null; setError(apiError?.code === "network" ? t("networkError") : t("genericError")); }, [t]);
  useEffect(() => { let live = true; setLoading(true); newsletterApi.preferences(token).then((value) => { if (!live) return; setData(value); setDraftPrefs(value.preferences || {}); setFrequency(value.frequency || "weekly"); if (value.status === "unsubscribed") setUnsubscribed(true); }).catch((e) => { if (!live) return; setError(e instanceof NewsletterApiError && [404, 410].includes(e.status) ? t("invalidToken") : e instanceof NewsletterApiError && e.code === "network" ? t("networkError") : t("genericError")); }).finally(() => live && setLoading(false)); return () => { live = false; }; }, [token, t]);
  const action = async (name: string, fn: () => Promise<void>) => { setBusy(name); setError(""); setNotice(""); try { await fn(); } catch (e) { fail(e); } finally { setBusy(""); } };
  const followedIds = useMemo(() => new Set((data?.stations || []).map((s) => String(stationValue(s).id))), [data?.stations]);
  if (loading) return <main className="newsletter-page"><p role="status">{t("loading")}</p></main>;
  if (!data) return <main className="newsletter-page"><div className="newsletter-feedback newsletter-feedback--error" role="alert">{error}</div></main>;
  if (unsubscribed) return <main className="newsletter-page"><div className="newsletter-hero"><h1>{t("preferencesTitle")}</h1><p>{t("unsubscribeDone")}</p></div></main>;
  const stations = data.stations || []; const alerts = data.alerts || [];
  const saveGeneral = (event: FormEvent) => { event.preventDefault(); void action("general", async () => { const updated = await newsletterApi.updatePreferences(token, { preferences: draftPrefs, frequency }); setData(updated); setDraftPrefs(updated.preferences); setFrequency(updated.frequency); setNotice(t("saved")); }); };
  return <main className="newsletter-page"><header className="newsletter-hero"><p className="eyebrow">Snow Explorer</p><h1>{t("preferencesTitle")}</h1>{data.email && <p>{data.email}</p>}</header>
    {(error || notice) && <div role={error ? "alert" : "status"} className={`newsletter-feedback newsletter-feedback--${error ? "error" : "success"}`}>{error || notice}</div>}
    <form className="newsletter-section" onSubmit={saveGeneral}><h2>{t("receive")}</h2><div className="preference-grid">{preferenceKeys.map((key) => <label className="preference-toggle" key={key}><span>{t(key === "weather" ? "weatherPref" : key)}</span><input type="checkbox" checked={Boolean(draftPrefs[key])} onChange={(e) => setDraftPrefs((old) => ({ ...old, [key]: e.target.checked }))} /></label>)}</div><h3>{t("frequency")}</h3><div className="newsletter-radio-list">{(["immediate", "weekly", "monthly"] as const).map((value) => <label key={value}><input type="radio" name="frequency" checked={frequency === value} onChange={() => setFrequency(value)} /><span>{t(value)}</span></label>)}</div><button className="btn btn--primary" disabled={busy === "general"}>{busy === "general" ? t("saving") : t("savePreferences")}</button></form>
    <section className="newsletter-section"><div className="newsletter-section__heading"><h2>{t("stations")}</h2><button type="button" className="btn btn--secondary" onClick={() => setAdding((v) => !v)}>+ {t("addStation")}</button></div>{adding && <StationSearch followedIds={followedIds} t={t} onSelect={async (station) => action("add", async () => { const confirmed = await newsletterApi.addStation(token, station.id); setData((old) => old ? { ...old, stations: [...old.stations, confirmed] } : old); setAdding(false); setNotice(t("followed")); })} />}{!stations.length ? <p className="newsletter-empty">{t("noStations")}</p> : <div className="followed-stations">{stations.map((station) => <FollowedStation key={stationValue(station).id} value={station} busy={busy} t={t} onSave={(settings) => action(`station-${stationValue(station).id}`, async () => { const confirmed = await newsletterApi.updateStation(token, stationValue(station).id, settings); setData((old) => old ? { ...old, stations: replaceById(old.stations.map((s) => ({ ...s, id: stationValue(s).id })), { ...confirmed, id: stationValue(confirmed).id }) } : old); setNotice(t("saved")); })} onRemove={() => action(`remove-${stationValue(station).id}`, async () => { await newsletterApi.removeStation(token, stationValue(station).id); setData((old) => old ? { ...old, stations: old.stations.filter((s) => String(stationValue(s).id) !== String(stationValue(station).id)), alerts: old.alerts.filter((a) => String(a.station_id) !== String(stationValue(station).id)) } : old); setNotice(t("removed")); })} />)}</div>}</section>
    <SnowAlerts token={token} stations={stations} alerts={alerts} busy={busy} t={t} action={action} setData={setData} />
    <section className="newsletter-section newsletter-danger"><h2>{t("unsubscribe")}</h2>{confirmUnsubscribe ? <div className="newsletter-confirm"><p>{t("unsubscribeConfirm")}</p><button className="btn btn--secondary" onClick={() => setConfirmUnsubscribe(false)}>{t("cancel")}</button><button className="btn newsletter-btn--danger" disabled={busy === "unsubscribe"} onClick={() => action("unsubscribe", async () => { await newsletterApi.unsubscribe(token); setUnsubscribed(true); })}>{t("confirm")}</button></div> : <button className="btn btn--secondary" onClick={() => setConfirmUnsubscribe(true)}>{t("unsubscribe")}</button>}</section>
  </main>;
}

function FollowedStation({ value, busy, t, onSave, onRemove }: { value: StationPreference; busy: string; t: any; onSave: (v: Pick<StationPreference, "weather" | "snow_conditions" | "resort_updates" | "weather_frequency">) => void; onRemove: () => void }) {
  const station = stationValue(value); const [open, setOpen] = useState(false); const [draft, setDraft] = useState({ weather: Boolean(value.weather), snow_conditions: Boolean(value.snow_conditions), resort_updates: Boolean(value.resort_updates), weather_frequency: value.weather_frequency || "disabled" }); const [confirming, setConfirming] = useState(false);
  useEffect(() => setDraft({ weather: Boolean(value.weather), snow_conditions: Boolean(value.snow_conditions), resort_updates: Boolean(value.resort_updates), weather_frequency: value.weather_frequency || "disabled" }), [value]);
  return <article className="followed-station"><header><h3>{station.name}</h3><div><button className="btn btn--secondary" onClick={() => setOpen((v) => !v)}>{t("configure")}</button><button className="btn btn--ghost" onClick={() => setConfirming(true)}>{t("remove")}</button></div></header>{confirming && <div className="newsletter-confirm"><p>{t("removeConfirm")}</p><button className="btn btn--secondary" onClick={() => setConfirming(false)}>{t("cancel")}</button><button className="btn newsletter-btn--danger" onClick={onRemove}>{t("confirm")}</button></div>}{open && <div className="station-settings">{[["weather", "weather"], ["snow_conditions", "snowConditions"], ["resort_updates", "importantInfo"]].map(([key, label]) => <label className="preference-toggle" key={key}><span>{t(label)}</span><input type="checkbox" checked={Boolean((draft as any)[key])} onChange={(e) => setDraft((old) => ({ ...old, [key]: e.target.checked }))} /></label>)}<label className="newsletter-field"><span>{t("weatherFrequency")}</span><select value={draft.weather_frequency} onChange={(e) => setDraft((old) => ({ ...old, weather_frequency: e.target.value as any }))}>{[["daily", "daily"], ["friday", "friday"], ["weekly", "weatherWeekly"], ["disabled", "weatherDisabled"]].map(([value, label]) => <option value={value} key={value}>{t(label)}</option>)}</select></label><button className="btn btn--primary" disabled={busy === `station-${station.id}`} onClick={() => onSave(draft)}>{t("save")}</button></div>}</article>;
}

function SnowAlerts({ token, stations, alerts, busy, t, action, setData }: { token: string; stations: StationPreference[]; alerts: SnowAlert[]; busy: string; t: any; action: any; setData: React.Dispatch<React.SetStateAction<NewsletterPreferencesData | null>> }) {
  const [stationId, setStationId] = useState(""); const [amount, setAmount] = useState("10"); const [period, setPeriod] = useState<24 | 48 | 72>(24); const [editing, setEditing] = useState<string | number | null>(null); const [validation, setValidation] = useState("");
  useEffect(() => { if (!stationId && stations[0]) setStationId(String(stationValue(stations[0]).id)); }, [stations, stationId]);
  const submit = (event: FormEvent) => { event.preventDefault(); const cm = Number(amount); if (!Number.isInteger(cm) || cm <= 0 || cm > 500 || !stationId) return setValidation(t("invalidAlert")); setValidation(""); const body = { station_id: stationId, snowfall_cm: cm, period_hours: period, active: true }; void action("alert", async () => { const confirmed = editing == null ? await newsletterApi.createAlert(token, body) : await newsletterApi.updateAlert(token, editing, body); setData((old) => old ? { ...old, alerts: editing == null ? [...old.alerts, confirmed] : replaceById(old.alerts, confirmed) } : old); setEditing(null); setAmount("10"); }); };
  return <section className="newsletter-section"><h2>{t("snowAlerts")}</h2>{stations.length > 0 && <form className="snow-alert-form" onSubmit={submit}><label className="newsletter-field"><span>{t("station")}</span><select value={stationId} onChange={(e) => setStationId(e.target.value)}>{stations.map((s) => { const station = stationValue(s); return <option value={station.id} key={station.id}>{station.name}</option>; })}</select></label><label className="newsletter-field"><span>{t("alertIntro")}</span><span className="newsletter-input-unit"><input type="number" min="1" max="500" value={amount} onChange={(e) => setAmount(e.target.value)} /> cm</span></label><label className="newsletter-field"><span>{t("forecastWithin")}</span><select value={period} onChange={(e) => setPeriod(Number(e.target.value) as 24 | 48 | 72)}>{[24, 48, 72].map((hours) => <option value={hours} key={hours}>{hours} {t("hours")}</option>)}</select></label>{validation && <p role="alert" className="newsletter-feedback--error">{validation}</p>}<button className="btn btn--primary" disabled={busy === "alert"}>{editing == null ? t("createAlert") : t("save")}</button></form>}<div className="snow-alert-list">{alerts.length ? alerts.map((alert) => { const station = alert.station || stationValue(stations.find((s) => String(stationValue(s).id) === String(alert.station_id)) || ({ id: alert.station_id, name: t("station") } as StationPreference)); return <article key={alert.id}><div><h3>❄ {station.name}</h3><p>{alert.snowfall_cm} {t("cmOrMore")} / {alert.period_hours} h · {alert.active === false ? t("disabled") : t("enabled")}</p></div><div><button className="btn btn--secondary" onClick={() => { setEditing(alert.id); setStationId(String(alert.station_id)); setAmount(String(alert.snowfall_cm)); setPeriod(alert.period_hours); }}>{t("edit")}</button>{typeof alert.active === "boolean" && <button className="btn btn--ghost" onClick={() => action(`toggle-${alert.id}`, async () => { const confirmed = await newsletterApi.updateAlert(token, alert.id, { active: !alert.active }); setData((old: NewsletterPreferencesData | null) => old ? { ...old, alerts: replaceById(old.alerts, confirmed) } : old); })}>{alert.active ? t("disabled") : t("enabled")}</button>}<button className="btn btn--ghost" onClick={() => action(`delete-${alert.id}`, async () => { await newsletterApi.removeAlert(token, alert.id); setData((old: NewsletterPreferencesData | null) => old ? { ...old, alerts: old.alerts.filter((a) => String(a.id) !== String(alert.id)) } : old); })}>{t("delete")}</button></div></article>; }) : <p className="newsletter-empty">{t("alertEmpty")}</p>}</div></section>;
}
