import React, { useCallback, useEffect, useMemo, useState } from "react";
import ForfaitsJsonImport from "./ForfaitsJsonImport";
import { getAdminSkiPasses, saveAdminSkiPassSeason, setAdminSkiPassSeasonActive } from "@/lib/api/skiPasses";
import type { SkiPassPrice, SkiPassSeason } from "@/types/skiPass";

const uid = () => `new-${Date.now()}-${Math.random().toString(36).slice(2)}`;
const iso = (value: string) => value || "";
const periodName = (period: SkiPassSeason["periods"][number]) => period.name || `Du ${period.start_date || "…"} au ${period.end_date || "…"}`;

export default function SkiPassEditor({ stationSlug }: { stationSlug: string }) {
  const [seasons, setSeasons] = useState<SkiPassSeason[]>([]), [seasonIndex, setSeasonIndex] = useState(0), [periodIndex, setPeriodIndex] = useState(0);
  const [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [notice, setNotice] = useState(""), [error, setError] = useState("");
  const reload = useCallback(async () => { setLoading(true); setError(""); try { const data = await getAdminSkiPasses(stationSlug); setSeasons(data.seasons.map(item => ({ ...item, is_active: item.is_active === true }))); setSeasonIndex(0); setPeriodIndex(0); } catch (e) { setError(e instanceof Error ? e.message : "Chargement impossible."); } finally { setLoading(false); } }, [stationSlug]);
  useEffect(() => { void reload(); }, [reload]);
  const season = seasons[seasonIndex];
  const categories = useMemo(() => { const map = new Map<string, string>(); season?.passes.forEach(product => product.prices.forEach(price => map.set(price.category, price.category_label || price.category))); return [...map].map(([category, label]) => ({ category, label })); }, [season]);
  const change = (recipe: (draft: SkiPassSeason) => void) => setSeasons(current => current.map((item, index) => { if (index !== seasonIndex) return item; const draft = structuredClone(item); recipe(draft); return draft; }));
  const priceFor = (productIndex: number, category: string) => season.passes[productIndex].prices.find(price => String(price.period_id) === String(season.periods[periodIndex]?.id) && price.category === category);
  const updatePrice = (productIndex: number, category: string, patch: Partial<SkiPassPrice>) => change(draft => { const product = draft.passes[productIndex]; let price = product.prices.find(value => String(value.period_id) === String(draft.periods[periodIndex]?.id) && value.category === category); if (!price) { price = { period_id: draft.periods[periodIndex]?.id, category, category_label: categories.find(c => c.category === category)?.label || category, price_type: "fixed", price: null, price_min: null, price_max: null }; product.prices.push(price); } Object.assign(price, patch); });
  const save = async () => { if (!season) return; setSaving(true); setError(""); setNotice(""); try { await saveAdminSkiPassSeason(stationSlug, season); await reload(); setNotice("Forfaits enregistrés avec succès."); } catch (e) { setError(e instanceof Error ? e.message : "Sauvegarde impossible."); } finally { setSaving(false); } };
  const togglePublicDisplay = async () => { if (!season) return; const seasonId = season.id; const isActive = !season.is_active; setSaving(true); setError(""); setNotice(""); try { const confirmedIsActive = await setAdminSkiPassSeasonActive(stationSlug, seasonId, isActive); setSeasons(current => current.map(item => item.id === seasonId ? { ...item, is_active: confirmedIsActive } : item)); setNotice("Affichage public mis à jour."); } catch (e) { setError(e instanceof Error ? e.message : "Impossible de modifier l’affichage public."); } finally { setSaving(false); } };

  return <div className="ski-pass-admin">
    {error && <div className="forfaits-import-errors" role="alert">{error}</div>}{notice && <div className="forfaits-import-result" role="status">{notice}</div>}
    {loading ? <p>Chargement des tarifs normalisés…</p> : !season ? <p>Aucune saison normalisée. Les données legacy restent visibles sur le site public jusqu’au premier import.</p> : <>
      <label className="ski-pass-admin__visibility"><span>Afficher ces forfaits sur le site</span><input type="checkbox" role="switch" checked={season.is_active} disabled={saving} onChange={() => void togglePublicDisplay()} /></label>
      {seasons.length > 1 && <label>Saison affichée<select value={seasonIndex} onChange={e => { setSeasonIndex(Number(e.target.value)); setPeriodIndex(0); }}>{seasons.map((item, index) => <option key={item.id} value={index}>{item.season}</option>)}</select></label>}
      <div className="ski-pass-admin__meta"><label>Saison<input value={season.season} onChange={e => change(d => { d.season = e.target.value; })} /></label><label>Devise<input value={season.currency} onChange={e => change(d => { d.currency = e.target.value; })} /></label><label>Source officielle<input type="url" value={season.source_url || ""} onChange={e => change(d => { d.source_url = e.target.value; })} /></label></div>
      <section><div className="ski-pass-admin__heading"><h3>Périodes tarifaires</h3><button type="button" className="btn btn--secondary" onClick={() => change(d => { d.periods.push({ id: uid(), start_date: "", end_date: "", sort_order: d.periods.length }); })}>Ajouter une période</button></div>
        <div className="ski-pass-admin__periods">{season.periods.map((period, index) => <div key={period.id || index}><strong>{periodName(period)}</strong><label>Début<input type="date" value={iso(period.start_date)} onChange={e => change(d => { d.periods[index].start_date = e.target.value; })} /></label><label>Fin<input type="date" value={iso(period.end_date)} onChange={e => change(d => { d.periods[index].end_date = e.target.value; })} /></label><button type="button" className="btn btn--secondary" onClick={() => change(d => { const [removed] = d.periods.splice(index, 1); d.passes.forEach(p => { p.prices = p.prices.filter(price => String(price.period_id) !== String(removed.id)); }); setPeriodIndex(0); })}>Supprimer</button></div>)}</div></section>
      <section><div className="ski-pass-admin__heading"><h3>Catégories</h3><button type="button" className="btn btn--secondary" onClick={() => { const category = uid(); change(d => d.passes.forEach(p => d.periods.forEach(period => p.prices.push({ period_id: period.id, category, category_label: "Nouvelle catégorie", price_type: "fixed", price: null, price_min: null, price_max: null })))); }}>Ajouter une catégorie</button></div>
        <div className="ski-pass-admin__categories">{categories.map(category => <div key={category.category}><input aria-label={`Libellé ${category.category}`} value={category.label} onChange={e => change(d => d.passes.forEach(p => p.prices.filter(x => x.category === category.category).forEach(x => { x.category_label = e.target.value; })))} /><button type="button" className="btn btn--secondary" onClick={() => change(d => d.passes.forEach(p => { p.prices = p.prices.filter(x => x.category !== category.category); }))}>Supprimer</button></div>)}</div></section>
      <section><div className="ski-pass-admin__heading"><h3>Forfaits</h3><button type="button" className="btn btn--secondary" onClick={() => change(d => { const id = uid(); d.passes.push({ id, name: "Nouveau forfait", duration_days: null, duration_label: "", sort_order: d.passes.length, prices: d.periods.flatMap(period => categories.map(c => ({ period_id: period.id, category: c.category, category_label: c.label, price_type: "fixed" as const, price: null, price_min: null, price_max: null }))) }); })}>Ajouter un produit</button></div>
        <label>Période<select value={periodIndex} onChange={e => setPeriodIndex(Number(e.target.value))}>{season.periods.map((period, index) => <option key={period.id || index} value={index}>{periodName(period)}</option>)}</select></label>
        <div className="ski-pass-admin__table"><table><thead><tr><th>Produit / durée</th>{categories.map(c => <th key={c.category}>{c.label}</th>)}<th>Actions</th></tr></thead><tbody>{season.passes.map((product, productIndex) => <tr key={product.id || productIndex}><th><input aria-label="Nom du produit" value={product.name} onChange={e => change(d => { d.passes[productIndex].name = e.target.value; })} /><input type="number" step="0.5" aria-label="Durée en jours" value={product.duration_days ?? ""} onChange={e => change(d => { d.passes[productIndex].duration_days = e.target.value === "" ? null : Number(e.target.value); })} /><input aria-label="Libellé de durée" value={product.duration_label} onChange={e => change(d => { d.passes[productIndex].duration_label = e.target.value; })} /><input type="number" aria-label="Ordre" value={product.sort_order} onChange={e => change(d => { d.passes[productIndex].sort_order = Number(e.target.value); })} /></th>{categories.map(category => { const price = priceFor(productIndex, category.category); const dynamic = price?.price_type === "dynamic"; return <td key={category.category}><select aria-label="Type de tarif" value={price?.price_type || "fixed"} onChange={e => updatePrice(productIndex, category.category, e.target.value === "dynamic" ? { price_type: "dynamic", price: null } : { price_type: "fixed", price_min: null, price_max: null })}><option value="fixed">Fixe</option><option value="dynamic">Dynamique</option></select>{dynamic ? <><input type="number" step="0.01" aria-label="Prix minimum" value={price?.price_min ?? ""} onChange={e => updatePrice(productIndex, category.category, { price_min: e.target.value === "" ? null : Number(e.target.value) })} /><input type="number" step="0.01" aria-label="Prix maximum" value={price?.price_max ?? ""} onChange={e => updatePrice(productIndex, category.category, { price_max: e.target.value === "" ? null : Number(e.target.value) })} /></> : <input type="number" step="0.01" aria-label="Prix" value={price?.price ?? ""} onChange={e => updatePrice(productIndex, category.category, { price: e.target.value === "" ? null : Number(e.target.value) })} />}<input aria-label="Note étoilée du tarif" placeholder="Texte de la note (facultatif)" value={price?.label || ""} onChange={e => updatePrice(productIndex, category.category, { label: e.target.value || null })} /></td>; })}<td><button type="button" className="btn btn--secondary" onClick={() => change(d => { d.passes.splice(productIndex, 1); })}>Supprimer</button></td></tr>)}</tbody></table></div>
      </section><button type="button" className="btn btn--primary" disabled={saving} onClick={() => void save()}>{saving ? "Enregistrement…" : "Enregistrer les forfaits"}</button>
    </>}
    <ForfaitsJsonImport stationSlug={stationSlug} season={season} onImported={async result => { await reload(); setNotice(`Import réussi — Saison ${result.season} : ${result.periods_count} période(s), ${result.passes_count} forfait(s), ${result.prices_count} tarif(s).`); }} />
  </div>;
}
