import { useCallback, useState } from "react";
import AccessibleModal from "./AccessibleModal";
import { ChangeList, FilePicker, ImportRules, MessageList, validateJsonFile } from "./ImportUi";
import { confirmStationImport, previewStationImport } from "@/lib/api/stationImports";
import type { ImportResult, StationImportPreview } from "@/types/stationImport";

export default function StationImportModal({ open, stationId, stationName, onClose, onImported }: { open: boolean; stationId: string; stationName: string; onClose: () => void; onImported: () => void | Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [fileError, setFileError] = useState(""); const [preview, setPreview] = useState<StationImportPreview | null>(null); const [result, setResult] = useState<ImportResult | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const reset = useCallback(() => { setFile(null); setFileError(""); setPreview(null); setResult(null); setError(""); }, []);
  const close = () => { if (busy) return; reset(); onClose(); };
  const select = (next: File | null) => { setPreview(null); setResult(null); setError(""); setFile(next); setFileError(next ? validateJsonFile(next) || "" : ""); };
  const analyze = async () => { if (!file) return; const invalid = validateJsonFile(file); if (invalid) { setFileError(invalid); return; } setBusy(true); setError(""); try { setPreview(await previewStationImport(stationId, file)); } catch (e) { setError(e instanceof Error ? e.message : "Analyse impossible."); } finally { setBusy(false); } };
  const blockers = !preview?.valid || !preview.preview_token || preview.changes.filter(c => c.action !== "unchanged").length === 0 || preview.errors.some(e => e.blocking !== false);
  const confirm = async () => { if (!file || !preview?.preview_token || blockers) return; setBusy(true); setError(""); try { const value = await confirmStationImport(stationId, file, preview.preview_token); setResult(value); await onImported(); } catch (e) { setError(e instanceof Error ? e.message : "Import impossible."); } finally { setBusy(false); } };
  const step = result ? 4 : preview ? 3 : 1;
  return <AccessibleModal open={open} title={`Importer un JSON — ${stationName}`} busy={busy} onClose={close}><div className="import-steps" aria-label="Progression"><span>Étape {step} sur 4</span><strong>{result ? "Résultat" : preview ? "Confirmation" : "Sélection du fichier"}</strong></div><div className="import-modal__body" aria-live="polite">{error && <div className="import-alert import-alert--error" role="alert">{error}</div>}{!result && <FilePicker file={file} onChange={select} error={fileError} />}{!preview && !result && <><ImportRules /><div className="import-actions"><button type="button" className="btn btn--primary" disabled={!file || !!fileError || busy} onClick={analyze}>{busy ? "Analyse…" : "Analyser le fichier"}</button></div></>}{preview && !result && <><div className="import-summary"><div><span>Station ciblée</span><strong>{preview.target?.name || stationName}</strong></div><div><span>Version du schéma</span><strong>{preview.schema_version || "Absente"}</strong></div><div><span>Changements</span><strong>{preview.changes.filter(c => c.action !== "unchanged").length}</strong></div><div><span>Champs inchangés</span><strong>{preview.unchanged_fields.length}</strong></div></div><MessageList title="Erreurs" messages={[...preview.errors, ...(preview.conflicts || [])]} /><MessageList title="Avertissements" messages={preview.warnings} warning /><ChangeList changes={preview.changes} /><p className="import-confirmation">Cette action modifiera la station {preview.target?.name || stationName} avec les changements présentés ci-dessus.</p><div className="import-actions"><button type="button" className="btn btn--secondary" disabled={busy} onClick={() => setPreview(null)}>Choisir un autre fichier</button><button type="button" className="btn btn--primary" disabled={blockers || busy} onClick={confirm}>{busy ? "Confirmation…" : "Confirmer la mise à jour"}</button></div></>}{result && <div className="import-result" role="status"><h3>{result.success ? "Import terminé" : "Import terminé avec des erreurs"}</h3>{result.message && <p>{result.message}</p>}<p>{result.updated_fields.length} champ(s) mis à jour.</p><ul>{result.updated_fields.map(x => <li key={x}>{x}</li>)}</ul><button type="button" className="btn btn--primary" onClick={close}>Revenir à la fiche</button></div>}</div></AccessibleModal>;
}
