import Link from "next/link";
import { useRouter } from "next/router";
import { Fragment, useEffect, useMemo, useState } from "react";
import { actionLabel, filterRowsForSelectedView, mappingLabel, workflowLabel } from "@/lib/anmsmCoverage";
import { exportAnmsmCoverage, getAnmsmCoverage } from "@/lib/adminCoverageApi";
import type { AnmsmCoverageResponse, CoverageView, SnowExplorerCoverageStation } from "@/types/anmsmCoverage";

export const COVERAGE_VIEWS: Array<[CoverageView, string]> = [
  ["todo", "À traiter"], ["all", "Toutes les stations Snow Explorer"], ["unmatched", "Stations non associées à ANMSM"], ["availability_control", "Disponibilité ANMSM à contrôler"], ["contact", "Stations à contacter"], ["logo_available", "Logos disponibles à récupérer"], ["map_available", "Plans disponibles à récupérer"], ["logo_prepare", "Logos à préparer"], ["map_prepare", "Plans à préparer"], ["logo_review", "Logos à vérifier"], ["map_review", "Plans à vérifier"], ["logo_published", "Logos publiés depuis ANMSM"], ["map_published", "Plans publiés depuis ANMSM"], ["errors", "Erreurs"], ["anmsm_only", "Stations uniquement chez ANMSM"]
];
const isView = (value: unknown): value is CoverageView => typeof value === "string" && COVERAGE_VIEWS.some(([view]) => view === value);

export default function AnmsmCoveragePage() {
  const router = useRouter();
  const [data, setData] = useState<AnmsmCoverageResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [exportError, setExportError] = useState(""); const [open, setOpen] = useState<string | null>(null);
  const view: CoverageView = isView(router.query.view) ? router.query.view : "todo";
  const search = typeof router.query.search === "string" ? router.query.search : "";
  const page = Math.max(1, Number(router.query.page) || 1);
  useEffect(() => { if (!router.isReady) return; let active = true; setLoading(true); getAnmsmCoverage().then(value => active && setData(value)).catch(reason => active && setError(reason instanceof Error ? reason.message : "Endpoint indisponible")).finally(() => active && setLoading(false)); return () => { active = false; }; }, [router.isReady]);
  const updateUrl = (next: { view?: CoverageView; search?: string; page?: number }) => { const values = { view, search, page, ...next }; void router.replace({ pathname: router.pathname, query: { view: values.view, ...(values.search && { search: values.search }), page: String(values.page) } }, undefined, { shallow: true }); };
  const selectedRows = useMemo(() => data && view !== "anmsm_only" ? filterRowsForSelectedView(data.snow_explorer_stations, view) : [], [data, view]);
  const normalizedSearch = search.trim().toLocaleLowerCase("fr");
  const searchedSnow = selectedRows.filter(row => row.station_name.toLocaleLowerCase("fr").includes(normalizedSearch));
  const searchedOnly = (data?.anmsm_only_stations || []).filter(row => row.anmsm_station_name.toLocaleLowerCase("fr").includes(normalizedSearch));
  const allVisible = view === "anmsm_only" ? searchedOnly : searchedSnow; const pageSize = 25; const totalPages = Math.max(1, Math.ceil(allVisible.length / pageSize)); const safePage = Math.min(page, totalPages); const visibleRows = allVisible.slice((safePage - 1) * pageSize, safePage * pageSize);
  const download = async () => { setExportError(""); try { const file = await exportAnmsmCoverage(); const url = URL.createObjectURL(file.blob); const a = document.createElement("a"); a.href = url; a.download = file.filename; a.click(); URL.revokeObjectURL(url); } catch (reason) { setExportError(reason instanceof Error ? reason.message : "Erreur de téléchargement CSV"); } };
  return <main className="anmsm-admin coverage-admin"><header className="anmsm-hero"><div><p className="eyebrow">Administration ANMSM</p><h1>Couverture ANMSM</h1></div></header>
    <div className="coverage-toolbar"><label>Afficher :<select aria-label="Afficher" value={view} onChange={event => updateUrl({ view: event.target.value as CoverageView, page: 1 })}>{COVERAGE_VIEWS.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Rechercher une station :<input aria-label="Rechercher une station" type="search" value={search} onChange={event => updateUrl({ search: event.target.value, page: 1 })} /></label>{view === "contact" && <button type="button" className="btn btn--secondary" onClick={() => void download()}>Exporter les stations à contacter</button>}</div>
    {exportError && <p className="notice notice--danger" role="alert">{exportError}</p>}{loading && <p>Chargement de la couverture…</p>}{error && <p className="notice notice--danger" role="alert">{error}</p>}
    {!loading && data && <><p className="coverage-result-count"><strong>{allVisible.length.toLocaleString("fr-FR")}</strong> résultat(s)</p>{view === "anmsm_only" ? <OnlyTable rows={visibleRows as AnmsmCoverageResponse["anmsm_only_stations"]} /> : <SnowTable rows={visibleRows as SnowExplorerCoverageStation[]} open={open} setOpen={setOpen} />}{totalPages > 1 && <nav className="anmsm-pagination" aria-label="Pagination"><span>Page {safePage} sur {totalPages}</span><button className="btn btn--secondary" disabled={safePage === 1} onClick={() => updateUrl({ page: safePage - 1 })}>Précédent</button><button className="btn btn--secondary" disabled={safePage === totalPages} onClick={() => updateUrl({ page: safePage + 1 })}>Suivant</button></nav>}</>}
  </main>;
}
function Detail({ row }: { row: SnowExplorerCoverageStation }) { const search = encodeURIComponent(row.station_name); const action = actionLabel(row); return <div className="coverage-detail-links">{action.includes("Associer") || action.includes("erreur") ? <Link href={`/admin/anmsm/logos?search=${search}`}>Gérer l’association</Link> : null}{action.toLocaleLowerCase("fr").includes("logo") && <Link href={`/admin/anmsm/logos?search=${search}`}>Ouvrir les logos</Link>}{action.toLocaleLowerCase("fr").includes("plan") && <Link href={`/admin/anmsm/piste-maps?search=${search}`}>Ouvrir les plans des pistes</Link>}{row.station_slug && <Link href={`/admin/stations/${encodeURIComponent(row.station_slug)}`}>Modifier la station</Link>}</div>; }
function SnowTable({ rows, open, setOpen }: { rows: SnowExplorerCoverageStation[]; open: string | null; setOpen: (id: string | null) => void }) { return <div className="anmsm-table-wrap"><table className="anmsm-table coverage-table"><thead><tr><th>Station</th><th>Association ANMSM</th><th>Logo</th><th>Plan des pistes</th><th>À faire</th></tr></thead><tbody>{rows.map(row => { const id = String(row.station_id); return <Fragment key={id}><tr className="coverage-clickable" onClick={() => setOpen(open === id ? null : id)}><td><strong>{row.station_name}</strong>{row.station_is_active === false && <small>inactive</small>}</td><td><strong>{mappingLabel(row.mapping_status)}</strong>{row.mapping_status === "matched" && row.anmsm_station_name && <small>{row.anmsm_station_name}</small>}</td><td>{workflowLabel(row.resources.logo.workflow_status, row.resources.logo)}</td><td>{workflowLabel(row.resources.piste_map.workflow_status, row.resources.piste_map)}</td><td><strong>{actionLabel(row)}</strong><button className="coverage-detail-button" type="button">Voir</button></td></tr>{open === id && <tr className="coverage-detail"><td colSpan={5}><Detail row={row} /></td></tr>}</Fragment>; })}</tbody></table>{rows.length === 0 && <p className="notice">Aucune station à afficher.</p>}</div>; }
function OnlyTable({ rows }: { rows: AnmsmCoverageResponse["anmsm_only_stations"] }) { return <div className="anmsm-table-wrap"><table className="anmsm-table coverage-only-table"><thead><tr><th>Station ANMSM</th><th>Logo</th><th>Plan des pistes</th><th>Suggestion</th><th>À faire</th></tr></thead><tbody>{rows.map(row => <tr key={row.anmsm_external_station_id}><td><strong>{row.anmsm_station_name}</strong></td><td>{row.logo_available == null ? "Disponibilité inconnue" : row.logo_available ? "Disponible" : "Absent chez ANMSM"}</td><td>{row.piste_map_available == null ? "Disponibilité inconnue" : row.piste_map_available ? "Disponible" : "Absent chez ANMSM"}</td><td>{row.suggestion ? <><strong>Suggestion non validée</strong><small>{typeof row.suggestion === "object" ? String(row.suggestion.station_name ?? row.suggestion.name ?? "") : row.suggestion}</small></> : "Aucune suggestion"}</td><td>Vérifier si la station existe dans Snow Explorer</td></tr>)}</tbody></table>{rows.length === 0 && <p className="notice">Aucune station à afficher.</p>}</div>; }
