import Link from "next/link";
import { useRouter } from "next/router";
import { FormEvent, Fragment, useEffect, useMemo, useState } from "react";
import { availabilityLabel, mappingLabel, requestLabel, workflowLabel } from "@/lib/anmsmCoverage";
import { exportAnmsmCoverage, getAnmsmCoverage } from "@/lib/adminCoverageApi";
import type { AnmsmCoverageResponse, CoverageFilter, CoverageQuery, CoverageResource, CoverageSort, SnowExplorerCoverageStation } from "@/types/anmsmCoverage";

const FILTERS: Array<[CoverageFilter, string, string?]> = [["all", "Toutes"], ["needs_contact", "À contacter", "stations_needing_contact"], ["availability_control", "Disponibilité à contrôler", "stations_needing_availability_control"], ["unmatched", "Non associées", "stations_unmatched"], ["missing_logo", "Logos manquants", "stations_without_usable_logo"], ["missing_piste_map", "Plans manquants", "stations_without_usable_piste_map"], ["available_anmsm", "Disponibles chez ANMSM"], ["to_prepare", "À préparer"], ["ready_to_review", "À vérifier"], ["published", "Publiées"], ["error", "Erreurs", "errors"], ["active", "Actives", "stations_active"], ["inactive", "Inactives", "stations_inactive"]];
const SORTS: Array<[CoverageSort, string]> = [["business", "Ordre métier"], ["name_asc", "Nom croissant"], ["name_desc", "Nom décroissant"], ["missing_resources", "Nombre de ressources manquantes"], ["coverage_status", "État de couverture"]];
const STAT_LABELS: Record<string, string> = { total_snow_explorer_stations: "Stations Snow Explorer", snow_explorer_stations_total: "Stations Snow Explorer", stations_active: "Stations actives", stations_inactive: "Stations inactives", stations_matched: "Stations associées", stations_unmatched: "Stations non associées", anmsm_only_stations: "Uniquement chez ANMSM", anmsm_only_stations_total: "Uniquement chez ANMSM", stations_needing_contact: "Stations à contacter", stations_needing_availability_control: "Disponibilités à contrôler", stations_without_usable_logo: "Sans logo exploitable", stations_without_usable_piste_map: "Sans plan exploitable", logos_available_not_imported: "Logos disponibles non récupérés", piste_maps_available_not_imported: "Plans disponibles non récupérés", logos_to_prepare: "Logos à préparer", piste_maps_to_prepare: "Plans à préparer", logos_ready_to_review: "Logos à vérifier", piste_maps_ready_to_review: "Plans à vérifier", logos_published_from_anmsm: "Logos publiés par ANMSM", piste_maps_published_from_anmsm: "Plans publiés par ANMSM", errors: "Erreurs" };
const show = (value: unknown) => typeof value === "string" || typeof value === "number" ? String(value) : "—";
const showDate = (value?: string | null) => value ? new Date(value).toLocaleString("fr-FR") : "Non renseignée";
const observed = (r: CoverageResource) => r.availability_status != null || r.available_from_anmsm != null || r.workflow_status != null;
const source = (r: CoverageResource) => !r.current_published_url ? "Aucune URL publiée" : r.published_source === "anmsm" ? "Publié depuis ANMSM" : !r.published_source || r.published_source === "unknown" ? "Présent — provenance inconnue" : `Présent — ${r.published_source}`;

function ResourceSummary({ resource }: { resource: CoverageResource }) { return !observed(resource) ? <span className="coverage-muted">Aucune observation ANMSM enregistrée</span> : <div className="coverage-resource"><span className={`coverage-badge coverage-badge--${resource.workflow_status || "neutral"}`}>{workflowLabel(resource.workflow_status)}</span><small>{availabilityLabel(resource.availability_status)}</small><small>{source(resource)}</small>{resource.error && <small className="coverage-error">Erreur : {resource.error}</small>}</div>; }
function ResourceDetail({ title, resource }: { title: string; resource: CoverageResource }) { const fields: Array<[string, unknown]> = [["Workflow", workflowLabel(resource.workflow_status)], ["Disponibilité", availabilityLabel(resource.availability_status)], ["URL publiée", resource.current_published_url], ["URL originale candidate", resource.candidate_original_url], ["URL d’aperçu candidate", resource.candidate_preview_url], ["Identifiant du candidat", resource.candidate_id], ["Statut du candidat", resource.candidate_status], ["Préparation nécessaire", resource.preparation_required == null ? "Non renseignée" : resource.preparation_required ? "Oui" : "Non"], ["Provenance publiée", source(resource)], ["Erreur exacte", resource.error], ["Raison du besoin de contact", resource.contact_reason]]; return <section><h4>État détaillé du {title}</h4>{!observed(resource) && <p className="coverage-observation">Aucune observation ANMSM enregistrée pour cette ressource. Effectuez d’abord les synchronisations prévues dans l’administration.</p>}<dl>{fields.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl></section>; }
function Actions({ row }: { row: SnowExplorerCoverageStation }) { const search = encodeURIComponent(row.station_name); return <div className="coverage-actions"><Link href={`/admin/anmsm/logos?search=${search}`}>Gérer l’association</Link><Link href={`/admin/anmsm/logos?search=${search}`}>Voir les logos</Link><Link href={`/admin/anmsm/piste-maps?search=${search}`}>Voir les plans des pistes</Link>{row.station_slug && <Link href={`/admin/stations/${encodeURIComponent(row.station_slug)}`}>Modifier la station</Link>}</div>; }

export default function AnmsmCoveragePage() {
  const router = useRouter(); const [data, setData] = useState<AnmsmCoverageResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [exportError, setExportError] = useState(""); const [open, setOpen] = useState<string | null>(null); const [searchDraft, setSearchDraft] = useState("");
  const query = useMemo<CoverageQuery>(() => ({ tab: router.query.tab === "anmsm_only" ? "anmsm_only" : "snow_explorer", search: typeof router.query.search === "string" ? router.query.search : "", filter: FILTERS.some(x => x[0] === router.query.filter) ? router.query.filter as CoverageFilter : "all", sort: SORTS.some(x => x[0] === router.query.sort) ? router.query.sort as CoverageSort : "business", page: Math.max(1, Number(router.query.page) || 1), page_size: [10, 20, 50, 100].includes(Number(router.query.page_size)) ? Number(router.query.page_size) : 20 }), [router.query]);
  useEffect(() => setSearchDraft(query.search), [query.search]);
  useEffect(() => { if (!router.isReady) return; let active = true; setLoading(true); setError(""); getAnmsmCoverage().then(value => { if (active) setData(value); }).catch(reason => { if (active) setError(reason instanceof Error ? reason.message : "Endpoint indisponible"); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [router.isReady]);
  const update = (next: Partial<CoverageQuery>, reset = true) => { const merged = { ...query, ...next, page: reset ? 1 : next.page ?? query.page }; void router.replace({ pathname: router.pathname, query: { tab: merged.tab, ...(merged.search && { search: merged.search }), ...(merged.filter !== "all" && { filter: merged.filter }), sort: merged.sort, page: String(merged.page), page_size: String(merged.page_size) } }, undefined, { shallow: true }); };
  const download = async () => { setExportError(""); try { const file = await exportAnmsmCoverage(); const url = URL.createObjectURL(file.blob); const a = document.createElement("a"); a.href = url; a.download = file.filename; a.click(); URL.revokeObjectURL(url); } catch (reason) { setExportError(reason instanceof Error ? reason.message : "Erreur de téléchargement CSV"); } };
  const pagination = query.tab === "snow_explorer" ? data?.snow_explorer_pagination : data?.anmsm_only_pagination;
  return <main className="anmsm-admin coverage-admin"><header className="anmsm-hero"><div><p className="eyebrow">Administration ANMSM</p><h1>Couverture ANMSM</h1><p>Contrôlez les associations et orientez le traitement des ressources sans modifier les données.</p></div><button type="button" className="btn btn--secondary" onClick={() => void download()}>Exporter les stations à contacter</button></header>
    {exportError && <p className="notice notice--danger" role="alert">Erreur de téléchargement CSV : {exportError}</p>}{data && <section className="anmsm-summary coverage-summary" aria-label="Compteurs globaux">{Object.entries(data.stats).map(([key, value]) => <div key={key}><strong>{value.toLocaleString("fr-FR")}</strong><span>{STAT_LABELS[key] || key.replaceAll("_", " ")}</span></div>)}</section>}
    <nav className="coverage-tabs" aria-label="Collections"><button className={query.tab === "snow_explorer" ? "is-active" : ""} onClick={() => update({ tab: "snow_explorer" })}>Stations Snow Explorer <strong>{data?.snow_explorer_pagination.total ?? 0}</strong></button><button className={query.tab === "anmsm_only" ? "is-active" : ""} onClick={() => update({ tab: "anmsm_only" })}>Uniquement chez ANMSM <strong>{data?.anmsm_only_pagination.total ?? 0}</strong></button></nav>
    <form className="coverage-toolbar" onSubmit={(event: FormEvent) => { event.preventDefault(); update({ search: searchDraft.trim() }); }}><label>Rechercher par nom<input type="search" value={searchDraft} onChange={event => setSearchDraft(event.target.value)} /></label><button className="btn btn--primary">Rechercher</button><label>Trier<select value={query.sort} onChange={event => update({ sort: event.target.value as CoverageSort })}>{SORTS.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><button type="button" className="btn btn--secondary" onClick={() => { setSearchDraft(""); update({ search: "", filter: "all", sort: "business", page_size: 20 }); }}>Réinitialiser</button></form>
    {query.tab === "snow_explorer" && <section className="anmsm-filters" aria-label="Filtres rapides">{FILTERS.map(([value, label, stat]) => <button key={value} type="button" className={`btn ${query.filter === value ? "btn--primary" : "btn--secondary"}`} aria-pressed={query.filter === value} onClick={() => update({ filter: value })}>{label}{stat && data?.stats[stat] != null ? ` (${data.stats[stat]})` : ""}</button>)}</section>}{query.filter !== "all" && <button type="button" className="coverage-clear" onClick={() => update({ filter: "all" })}>Retirer le filtre « {FILTERS.find(x => x[0] === query.filter)?.[1]} » ×</button>}
    {loading && <p aria-live="polite">Chargement de la couverture…</p>}{error && <p className="notice notice--danger" role="alert">{error}</p>}
    {!loading && data && (query.tab === "snow_explorer" ? <SnowTable data={data} open={open} setOpen={setOpen} /> : <OnlyTable data={data} />)}
    {pagination && <nav className="anmsm-pagination" aria-label="Pagination"><span>{pagination.total} résultat(s) · page {pagination.page} sur {Math.max(1, pagination.total_pages)}</span><label>Lignes par page<select value={query.page_size} onChange={event => update({ page_size: Number(event.target.value) })}>{[10, 20, 50, 100].map(n => <option key={n}>{n}</option>)}</select></label><button className="btn btn--secondary" disabled={pagination.page <= 1} onClick={() => update({ page: pagination.page - 1 }, false)}>Précédent</button><button className="btn btn--secondary" disabled={pagination.total_pages === 0 || pagination.page >= pagination.total_pages} onClick={() => update({ page: pagination.page + 1 }, false)}>Suivant</button></nav>}
  </main>;
}

function SnowTable({ data, open, setOpen }: { data: AnmsmCoverageResponse; open: string | null; setOpen: (value: string | null) => void }) { return <div className="anmsm-table-wrap"><table className="anmsm-table coverage-table"><thead><tr><th>Station Snow Explorer</th><th>État</th><th>Correspondance ANMSM</th><th>Logo</th><th>Plan des pistes</th><th>À demander</th><th>Couverture</th><th>Actions</th></tr></thead><tbody>{data.snow_explorer_stations.map(row => { const id = String(row.station_id); const meta: Array<[string, unknown]> = [["Identifiant Snow Explorer", row.station_id], ["Slug Snow Explorer", row.station_slug], ["Identifiant ANMSM", row.anmsm_external_station_id], ["Nom ANMSM", row.anmsm_station_name], ["Statut du mapping", mappingLabel(row.mapping_status)], ["Mapping validé", row.mapping_validated == null ? "Non renseigné" : row.mapping_validated ? "Oui" : "Non"], ["Dernière observation", showDate(row.last_anmsm_sync_at)]]; return <Fragment key={id}><tr><td data-label="Station Snow Explorer"><strong>{row.station_name}</strong><small>{show(row.station_slug)}</small></td><td data-label="État">{row.station_is_active == null ? "Non renseigné" : row.station_is_active ? "Active" : "Inactive"}</td><td data-label="Correspondance ANMSM"><span className="coverage-badge">{mappingLabel(row.mapping_status)}</span><small>{show(row.anmsm_station_name)}</small></td><td data-label="Logo"><ResourceSummary resource={row.resources.logo} /></td><td data-label="Plan des pistes"><ResourceSummary resource={row.resources.piste_map} /></td><td data-label="À demander"><strong className={row.needs_station_contact ? "coverage-contact" : ""}>{requestLabel(row)}</strong></td><td data-label="Couverture">{show(row.coverage_status)}</td><td data-label="Actions"><Actions row={row} /><button type="button" className="coverage-detail-button" aria-expanded={open === id} onClick={() => setOpen(open === id ? null : id)}>{open === id ? "Fermer le détail" : "Voir le détail"}</button></td></tr>{open === id && <tr className="coverage-detail"><td colSpan={8}><dl>{meta.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl><div className="coverage-resource-details"><ResourceDetail title="logo" resource={row.resources.logo} /><ResourceDetail title="plan" resource={row.resources.piste_map} /></div></td></tr>}</Fragment>; })}</tbody></table>{data.snow_explorer_stations.length === 0 && <p className="notice">Aucune station Snow Explorer à afficher.</p>}</div>; }
function OnlyTable({ data }: { data: AnmsmCoverageResponse }) { return <div className="anmsm-table-wrap"><table className="anmsm-table coverage-table coverage-only-table"><thead><tr><th>Station ANMSM</th><th>Identifiant ANMSM</th><th>Logo</th><th>Plan des pistes</th><th>Suggestion Snow Explorer</th><th>Dernière observation</th><th>Statut</th></tr></thead><tbody>{data.anmsm_only_stations.map(row => <tr key={row.anmsm_external_station_id}><td data-label="Station ANMSM"><strong>{row.anmsm_station_name}</strong><small>{show(row.anmsm_station_slug)}</small></td><td data-label="Identifiant ANMSM">{row.anmsm_external_station_id}</td><td data-label="Logo">{row.logo_available == null ? "Disponibilité inconnue" : row.logo_available ? "Disponible chez ANMSM" : "Non disponible chez ANMSM"}</td><td data-label="Plan des pistes">{row.piste_map_available == null ? "Disponibilité inconnue" : row.piste_map_available ? "Disponible chez ANMSM" : "Non disponible chez ANMSM"}</td><td data-label="Suggestion Snow Explorer">{row.suggestion ? <><strong>Suggestion non validée</strong><small>{show(typeof row.suggestion === "object" ? row.suggestion.station_name ?? row.suggestion.name : row.suggestion)}</small></> : "Aucune suggestion"}</td><td data-label="Dernière observation">{showDate(row.last_seen_at)}</td><td data-label="Statut">{show(row.status)}</td></tr>)}</tbody></table>{data.anmsm_only_stations.length === 0 && <p className="notice">Aucune station exclusivement ANMSM à afficher.</p>}</div>; }
