import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { approvePisteMaps, confirmPisteMapMapping, getPisteMapWorkspace, preparePisteMap, searchPisteMapResorts } from "@/lib/adminPisteMapsApi";
import { EMPTY_PISTE_MAP_STATS, paginatePisteMaps, pisteMapReady } from "@/lib/anmsmPisteMaps";
import type { PisteMapResort, PisteMapRow, PisteMapWorkspace } from "@/types/anmsmPisteMap";

type Filter = "review" | "prepare" | "mapping" | "published" | "problems" | "all";
const FILTERS: Array<[Filter, string]> = [["review", "Plans à vérifier"], ["prepare", "Plans à récupérer"], ["mapping", "Stations à associer"], ["published", "Plans publiés"], ["problems", "Problèmes"], ["all", "Tous"]];
const keyOf = (row: PisteMapRow) => `${row.external_station_id}:${row.external_map_id}`;
const category = (row: PisteMapRow): Exclude<Filter, "all"> => row.candidate_status === "approved" ? "published" : row.candidate_status === "error" || !!row.candidate?.error_message || row.warnings.some(w => w.blocking) ? "problems" : !row.mapping ? "mapping" : row.preparation_required ? "prepare" : "review";
const message = (error: unknown, action: "prepare" | "publish" | "download" = "download") => { const raw = error instanceof Error ? error.message : "Erreur inconnue"; if (/413|too large|taille/i.test(raw)) return "Plan trop lourd."; if (/format|mime|415/i.test(raw)) return "Format non pris en charge."; if (/illisible|decode|corrupt/i.test(raw)) return "Plan illisible."; return action === "prepare" ? "Préparation interrompue." : action === "publish" ? "Publication impossible." : "Téléchargement impossible."; };

function Preview({ src, title, credit, onOpen }: { src: string | null; title: string; credit: string | null; onOpen: () => void }) {
  return src ? <figure className="piste-map-preview"><button type="button" onClick={onOpen} aria-label={`Agrandir ${title}`}><img src={src} alt={title} /></button>{credit && <figcaption>Crédit : {credit}</figcaption>}</figure> : <span className="piste-map-muted">Plan absent</span>;
}
function MapModal({ src, title, credit, onClose }: { src: string; title: string; credit: string | null; onClose: () => void }) {
  const [wide, setWide] = useState(false); const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const escape = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [onClose]);
  return <div className="piste-map-modal-backdrop" role="presentation" onClick={onClose}><div className={`piste-map-modal ${wide ? "is-wide" : ""}`} role="dialog" aria-modal="true" aria-labelledby="piste-map-title" onClick={event => event.stopPropagation()}><header><strong id="piste-map-title">{title}</strong><button type="button" onClick={() => setWide(value => !value)}>{wide ? "Réduire" : "Pleine largeur"}</button><button ref={closeRef} type="button" onClick={onClose} aria-label="Fermer l’aperçu">×</button></header><div><img src={src} alt={title} /></div>{credit && <p>Crédit : {credit}</p>}</div></div>;
}
function Mapping({ row, onChoose }: { row: PisteMapRow; onChoose: (resort: PisteMapResort) => Promise<void> }) {
  const [query, setQuery] = useState(""); const [items, setItems] = useState<PisteMapResort[]>([]); const [busy, setBusy] = useState(false);
  const search = async (value: string) => { setQuery(value); if (value.trim().length < 2) { setItems([]); return; } try { setItems(await searchPisteMapResorts(value.trim())); } catch { setItems([]); } };
  if (row.mapping) return <><strong>{row.mapping.station_name}</strong><small>{row.mapping.station_id}</small></>;
  const choose = (resort: PisteMapResort) => { setBusy(true); void onChoose(resort).finally(() => setBusy(false)); };
  return <div className="anmsm-inline-picker">{row.suggestion?.station_id && <button type="button" disabled={busy} onClick={() => choose(row.suggestion!)}>{row.suggestion.station_name}</button>}<label>Rechercher une station Snow Explorer<input value={query} disabled={busy} onChange={event => void search(event.target.value)} /></label>{items.length > 0 && <ul>{items.map(item => <li key={item.station_id}><button type="button" disabled={busy} onClick={() => choose(item)}>{item.station_name}<small>{item.station_id}</small></button></li>)}</ul>}</div>;
}

export default function PisteMapsAdmin() {
  const [rows, setRows] = useState<PisteMapRow[]>([]); const [stats, setStats] = useState(EMPTY_PISTE_MAP_STATS); const [loaded, setLoaded] = useState(false);
  const [selected, setSelected] = useState<Set<number>>(new Set()); const [errors, setErrors] = useState<Record<string, string>>({}); const [notice, setNotice] = useState("");
  const [progress, setProgress] = useState({ done: 0, total: 0 }); const [running, setRunning] = useState(false); const runningRef = useRef(false);
  const [filter, setFilter] = useState<Filter>("review"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState<number | "all">(20);
  const [modal, setModal] = useState<{ src: string; title: string; credit: string | null } | null>(null);
  const replace = useCallback((next: PisteMapRow) => setRows(current => current.map(row => keyOf(row) === keyOf(next) ? next : row)), []);
  const refresh = useCallback(async () => { try { const data = await getPisteMapWorkspace(); setRows(data.rows); setStats(data.stats); setLoaded(true); setNotice(data.contractError || ""); return data; } catch (error) { setLoaded(true); setNotice(message(error)); return null; } }, []);
  useEffect(() => { void refresh(); }, [refresh]);
  const prepareOne = useCallback(async (row: PisteMapRow) => { try { const next = await preparePisteMap(row); replace(next); setErrors(current => { const copy = { ...current }; delete copy[keyOf(row)]; return copy; }); return true; } catch (error) { setErrors(current => ({ ...current, [keyOf(row)]: message(error, "prepare") })); return false; } }, [replace]);
  const prepareAll = useCallback(async (workspace: PisteMapWorkspace) => { if (runningRef.current) return; runningRef.current = true; setRunning(true); const queue = workspace.rows.filter(row => row.preparation_required === true); setProgress({ done: 0, total: queue.length }); for (let index = 0; index < queue.length; index += 1) { await prepareOne(queue[index]); setProgress({ done: index + 1, total: queue.length }); } runningRef.current = false; setRunning(false); }, [prepareOne]);
  const retrieve = async () => { const freshWorkspace = await refresh(); if (freshWorkspace) await prepareAll(freshWorkspace); };
  const associate = async (row: PisteMapRow, resort: PisteMapResort) => { try { const result = await confirmPisteMapMapping(row.external_station_id, resort.station_id); if (!result.ok || result.results?.some(item => !item.ok)) throw new Error("Association impossible"); const fresh = await refresh(); const updated = fresh?.rows.find(item => keyOf(item) === keyOf(row)); if (updated?.preparation_required) await prepareOne(updated); } catch (error) { setErrors(current => ({ ...current, [keyOf(row)]: message(error) })); } };
  const toggle = (row: PisteMapRow) => { if (row.candidate_id === null) return; setSelected(current => { const next = new Set(current); for (const item of rows) if (item.external_station_id === row.external_station_id && item.candidate_id !== null) next.delete(item.candidate_id); if (!current.has(row.candidate_id!)) next.add(row.candidate_id!); return next; }); };
  const publish = async () => { const candidate_ids = [...selected]; if (!candidate_ids.length) return; try { const result = await approvePisteMaps(candidate_ids); const succeeded = new Set(result.results.filter(item => item.ok).map(item => item.candidate_id)); setRows(current => current.map(row => row.candidate_id !== null && succeeded.has(row.candidate_id) ? { ...row, candidate_status: "approved", current_map_url: row.candidate?.display_url || row.current_map_url, current_map_width: row.candidate?.width || null, current_map_height: row.candidate?.height || null, current_map_size_bytes: row.candidate?.size_bytes || null, current_map_credit: row.candidate?.credit || null, candidate: row.candidate && { ...row.candidate, status: "published" } } : row)); setSelected(current => new Set([...current].filter(id => !succeeded.has(id)))); setErrors(current => ({ ...current, ...Object.fromEntries(result.results.filter(item => !item.ok).map(item => [String(item.candidate_id), message(item.error, "publish")])) })); setNotice(result.failed ? `${result.succeeded} plan(s) publié(s), ${result.failed} publication(s) impossible(s).` : `${result.succeeded} plan(s) publié(s).`); } catch (error) { setNotice(message(error, "publish")); } };
  const safeRows = useMemo(() => Array.isArray(rows) ? rows.filter(Boolean) : [], [rows]); const filtered = useMemo(() => safeRows.filter(row => filter === "all" || category(row) === filter), [safeRows, filter]);
  const effectiveSize = pageSize === "all" ? Math.max(1, filtered.length) : pageSize; const pages = Math.max(1, Math.ceil(filtered.length / effectiveSize)); const currentPage = Math.min(page, pages); const visible = useMemo(() => paginatePisteMaps(filtered, currentPage, effectiveSize), [filtered, currentPage, effectiveSize]);
  const ready = safeRows.filter(pisteMapReady); const open = (src: string | null, title: string, credit: string | null) => src && setModal({ src, title, credit });
  return <main className="anmsm-admin piste-maps-admin"><header className="anmsm-hero"><div><p className="eyebrow">Administration</p><h1>Plans des pistes ANMSM</h1></div><button className="btn btn--primary" disabled={running} onClick={() => void retrieve()}>Récupérer les plans des pistes ANMSM</button></header>
    <section className="anmsm-summary piste-map-summary" aria-label="Résumé"><div><strong>{stats.maps_to_review}</strong><span>Plans à vérifier</span></div><div><strong>{stats.maps_to_prepare}</strong><span>Plans à récupérer</span></div><div><strong>{stats.stations_to_map}</strong><span>Stations à associer</span></div><div><strong>{stats.maps_published}</strong><span>Plans publiés</span></div></section>
    {(stats.maps_missing > 0 || stats.errors > 0) && <p className="piste-map-secondary">Informations secondaires : {stats.maps_missing} plan(s) absent(s), {stats.errors} erreur(s).</p>}{notice && <p className="notice" role="status">{notice}</p>}
    {(running || progress.total > 0) && <section className="anmsm-progress" aria-live="polite"><strong>Préparation des plans : {progress.done} sur {progress.total}</strong><progress value={progress.done} max={progress.total || 1} /></section>}
    {loaded && <><section className="anmsm-filters" aria-label="Filtrer les plans">{FILTERS.map(([value, label]) => <button key={value} className={`btn ${filter === value ? "btn--primary" : "btn--secondary"}`} onClick={() => { setFilter(value); setPage(1); }}>{label}</button>)}</section>
    <section className="anmsm-selection"><button className="btn btn--secondary" onClick={() => { const byStation = new Map<string, number>(); ready.forEach(row => row.candidate_id !== null && !byStation.has(row.external_station_id) && byStation.set(row.external_station_id, row.candidate_id)); setSelected(new Set(byStation.values())); }}>Tout sélectionner</button><button className="btn btn--secondary" onClick={() => setSelected(new Set())}>Tout décocher</button><strong>{selected.size} plan(s) sélectionné(s)</strong><button className="btn btn--primary" disabled={!selected.size} onClick={() => void publish()}>Publier les plans sélectionnés</button></section>
    <div className="anmsm-table-wrap"><table className="anmsm-table piste-map-table"><thead><tr><th>Sélection</th><th>Station ANMSM</th><th>Station Snow Explorer associée</th><th>Titre ou type</th><th>Plan actuellement publié</th><th>Nouveau plan ANMSM</th><th>Dimensions et poids</th><th>Avertissements</th><th>État</th></tr></thead><tbody>{visible.map((row, index) => { const id = row.candidate_id; const selectedHere = id !== null && selected.has(id); const rowError = errors[keyOf(row)] || (id === null ? "" : errors[String(id)]) || row.candidate?.error_message; return <tr key={keyOf(row)} className={index > 0 && visible[index - 1].external_station_id === row.external_station_id ? "same-station" : ""}><td data-label="Sélection"><input type="checkbox" disabled={!pisteMapReady(row)} checked={selectedHere} onChange={() => toggle(row)} aria-label={`Sélectionner ${row.title}`} />{selectedHere && <small>Plan principal sélectionné</small>}</td><td data-label="Station ANMSM"><strong>{row.external_station_name}</strong></td><td data-label="Station associée"><Mapping row={row} onChoose={resort => associate(row, resort)} /></td><td data-label="Titre"><strong>{row.title}</strong>{row.map_type && <small>{row.map_type}</small>}</td><td data-label="Plan actuel"><Preview src={row.current_map_url} title={`Plan actuellement publié de ${row.external_station_name}`} credit={row.current_map_credit} onOpen={() => open(row.current_map_url, row.title, row.current_map_credit)} /></td><td data-label="Nouveau plan"><Preview src={row.candidate?.display_url || null} title={`Nouveau plan ANMSM de ${row.external_station_name}`} credit={row.candidate?.credit || null} onOpen={() => open(row.candidate?.display_url || null, row.title, row.candidate?.credit || null)} /></td><td data-label="Dimensions et poids"><small>{row.candidate?.width && row.candidate?.height ? `${row.candidate.width} × ${row.candidate.height} px` : "Dimensions inconnues"}</small><small>{row.candidate?.size_bytes == null ? "Poids inconnu" : `${(row.candidate.size_bytes / 1024 / 1024).toLocaleString("fr-FR", { maximumFractionDigits: 2 })} Mo`}</small></td><td data-label="Avertissements">{row.warnings.length ? row.warnings.map(item => <small key={`${item.code}:${item.message}`}>{item.message || "À contrôler"}</small>) : <small>Aucun</small>}</td><td data-label="État"><span className="anmsm-status">{row.candidate_status === "approved" ? "Plan publié" : category(row) === "review" ? "À vérifier" : category(row) === "prepare" ? "À récupérer" : category(row) === "mapping" ? "À associer" : "Problème"}</span>{rowError && <small className="anmsm-row-error" role="alert">{rowError}</small>}</td></tr>; })}</tbody></table></div>
    {filtered.length === 0 ? <p className="notice">Aucun plan à afficher.</p> : <nav className="anmsm-pagination" aria-label="Pagination"><label>Résultats par page <select value={pageSize} onChange={event => { setPageSize(event.target.value === "all" ? "all" : Number(event.target.value)); setPage(1); }}><option value={20}>20</option><option value={50}>50</option><option value={100}>100</option><option value="all">Tous</option></select></label><span>{filtered.length} résultat(s)</span><button className="btn btn--secondary" disabled={currentPage === 1} onClick={() => setPage(value => value - 1)}>Page précédente</button><strong>Page {currentPage} sur {pages}</strong><button className="btn btn--secondary" disabled={currentPage === pages} onClick={() => setPage(value => value + 1)}>Page suivante</button></nav>}</>}{modal && <MapModal {...modal} onClose={() => setModal(null)} />}</main>;
}
