import LegalPageLayout from "@/components/legal/LegalPageLayout";
import Link from "next/link";

export default function ConditionsUtilisationPage() {
  return <LegalPageLayout title="Conditions générales d'utilisation de Snow Explorer" pageTitle="CGU | Snow Explorer" description="Conditions générales d'utilisation du site Snow Explorer." canonicalPath="/conditions-utilisation">
    <section><h2>1. Objet</h2><p>Les présentes Conditions Générales d'Utilisation, ci-après les « CGU », ont pour objet de définir les conditions d'accès et d'utilisation du site Snow Explorer, ci-après le « Site ».</p><p>Snow Explorer est un service d'information consacré notamment aux stations de ski, domaines skiables, pistes, remontées mécaniques, conditions d'enneigement, météo, périodes d'ouverture, tarifs, webcams, plans des pistes et, plus généralement, aux informations pouvant être utiles à la préparation d'un séjour ou d'une activité en montagne.</p><p>Le Site est édité par 2DOLIST SAS.</p><p>L'utilisation du Site implique l'acceptation des présentes CGU.</p></section>
    <section><h2>2. Nature informative du Site</h2><p>Snow Explorer est un site d'information.</p><p>Les informations disponibles sur le Site sont fournies à titre indicatif et ne constituent pas une information officielle émanant des stations, domaines skiables, offices de tourisme, exploitants de remontées mécaniques, services météorologiques ou autres organismes mentionnés sur le Site, sauf lorsque cela est expressément indiqué.</p><p>Snow Explorer n'est pas le site officiel des stations de ski ou domaines skiables présentés.</p><p>Lorsqu'un lien vers un site officiel est proposé, l'utilisateur est invité à consulter cette source avant de prendre une décision fondée sur une information susceptible d'avoir évolué.</p></section>
    <section><h2>3. Exactitude et actualisation des informations</h2><p>2DOLIST SAS s'efforce de proposer des informations aussi fiables et à jour que possible.</p><p>Toutefois, les informations relatives aux stations et domaines skiables peuvent évoluer rapidement et sans que Snow Explorer en soit informé immédiatement.</p><p>Cela concerne notamment, sans que cette liste soit exhaustive :</p><ul><li>les dates et horaires d'ouverture ou de fermeture ;</li><li>l'ouverture ou la fermeture des pistes ;</li><li>l'ouverture ou la fermeture des remontées mécaniques ;</li><li>les conditions d'enneigement ;</li><li>les hauteurs de neige ;</li><li>les prévisions et conditions météorologiques ;</li><li>les tarifs des forfaits ;</li><li>les conditions d'accès ;</li><li>les restrictions d'exploitation ;</li><li>les équipements et services disponibles ;</li><li>les plans des pistes ;</li><li>les caractéristiques et le nombre de pistes ou de remontées mécaniques ;</li><li>les webcams ;</li><li>les événements ;</li><li>les informations communiquées par les stations ou par des sources tierces.</li></ul><p>Certaines informations peuvent également provenir de sources tierces ou de données publiées antérieurement.</p><p>Une information affichée sur Snow Explorer ne doit donc pas être considérée comme une garantie de sa validité au moment où l'utilisateur consulte le Site ou au moment de son séjour.</p></section>
    <section><h2>4. Vérification auprès des sources officielles</h2><p>Il appartient à l'utilisateur de vérifier auprès de la station, du domaine skiable, de l'office de tourisme, de l'exploitant concerné ou de toute autre source officielle les informations déterminantes avant d'effectuer une réservation, un déplacement ou toute autre dépense.</p><p>Cette vérification est particulièrement recommandée concernant les dates d'ouverture et de fermeture, l'état des pistes, l'enneigement, la météo, les tarifs, les conditions d'accès et la disponibilité des activités ou équipements.</p><p>Les liens vers les sites officiels proposés sur Snow Explorer ont notamment pour objectif de faciliter cette vérification.</p><p>L'utilisateur ne doit pas prendre une décision engageant des frais importants sur la seule base d'une information publiée sur Snow Explorer lorsqu'une confirmation auprès de la source officielle est possible.</p></section>
    <section><h2>5. Dates d'ouverture et de fermeture</h2><p>Les dates d'ouverture et de fermeture affichées sur Snow Explorer sont données à titre indicatif.</p><p>Elles peuvent être modifiées par les exploitants, notamment en fonction des conditions météorologiques, de l'enneigement, de contraintes techniques, de décisions administratives ou de toute autre circonstance affectant l'exploitation du domaine.</p><p>La présence d'une date d'ouverture ou de fermeture sur Snow Explorer ne garantit donc pas que la station, le domaine, une piste ou une remontée mécanique sera effectivement accessible à cette date.</p><p>L'utilisateur doit vérifier les dates et conditions d'ouverture sur le site officiel de la station ou auprès de l'exploitant avant d'organiser son déplacement ou son séjour.</p></section>
    <section><h2>6. Météo, neige et conditions de pratique</h2><p>Les informations météorologiques, prévisions, données d'enneigement et informations concernant les conditions de pratique sont susceptibles d'évoluer rapidement.</p><p>Elles peuvent provenir de services tiers et ne constituent pas une garantie des conditions qui seront effectivement constatées sur place.</p><p>Les conditions en montagne peuvent varier fortement selon l'altitude, l'exposition, le secteur et l'heure de la journée.</p><p>Snow Explorer ne doit pas être utilisé comme seul outil permettant de déterminer les conditions de sécurité nécessaires à la pratique d'une activité en montagne.</p><p>L'utilisateur doit consulter les informations officielles et adaptées à l'activité qu'il envisage avant sa pratique.</p></section>
    <section><h2>7. Plans des pistes et cartes</h2><p>Snow Explorer peut afficher des plans, cartes, images ou liens vers des plans de pistes fournis par des stations ou par des services tiers.</p><p>Ces éléments sont fournis à titre informatif.</p><p>Les plans peuvent être modifiés par leurs éditeurs sans que la version présentée ou référencée sur Snow Explorer soit immédiatement actualisée.</p><p>Lorsque Snow Explorer fournit un lien vers le plan officiel d'une station ou d'un domaine, l'utilisateur est invité à consulter cette version officielle pour disposer des informations les plus récentes.</p><p>Les plans et cartes disponibles sur le Site ne doivent pas être utilisés comme unique moyen d'orientation ou de sécurité sur le terrain.</p></section>
    <section><h2>8. Responsabilité</h2><p>Dans les limites autorisées par la législation applicable, 2DOLIST SAS ne saurait être tenue responsable des conséquences résultant exclusivement de l'utilisation d'une information devenue obsolète, modifiée par sa source ou différente de la situation effectivement constatée sur place lorsque cette évolution ne pouvait raisonnablement être connue ou intégrée par Snow Explorer.</p><p>En particulier, Snow Explorer ne garantit pas qu'une station, une piste, une remontée mécanique, un service ou une activité sera ouvert ou disponible à une date donnée.</p><p>2DOLIST SAS ne saurait notamment garantir l'absence d'évolution entre la publication ou la mise à jour d'une information et sa consultation par l'utilisateur.</p><p>Il appartient à l'utilisateur de procéder aux vérifications nécessaires auprès des sources officielles avant toute réservation, déplacement ou engagement financier.</p><p>Aucune disposition des présentes CGU n'a pour objet d'exclure ou de limiter une responsabilité qui ne pourrait légalement être exclue ou limitée.</p></section>
    <section><h2>9. Sites et services tiers</h2><p>Snow Explorer peut contenir des liens permettant d'accéder à des sites internet ou services exploités par des tiers.</p><p>Ces sites sont indépendants de Snow Explorer et restent sous la responsabilité de leurs éditeurs respectifs.</p><p>2DOLIST SAS ne contrôle pas en permanence leur contenu, leur disponibilité, leurs tarifs, leurs conditions contractuelles ou leurs politiques de confidentialité.</p><p>L'utilisateur est invité à consulter les conditions applicables sur le site tiers avant d'effectuer une réservation, un achat ou de transmettre des informations personnelles.</p></section>
    <section><h2>10. Publicité</h2><p>Snow Explorer peut afficher des contenus publicitaires.</p><p>La présence d'une publicité ne signifie pas nécessairement que Snow Explorer recommande personnellement le produit, le service ou l'entreprise concernée.</p><p>Les offres, prix, disponibilités, conditions et engagements figurant dans les publicités relèvent de l'annonceur concerné.</p><p>Lorsqu'un contenu constitue une communication commerciale et que son caractère commercial ne ressort pas déjà clairement du contexte, une indication appropriée peut être affichée afin de permettre à l'utilisateur de l'identifier.</p></section>
    <section><h2>11. Liens affiliés</h2><p>Certains liens présents sur Snow Explorer peuvent être des liens affiliés.</p><p>Lorsqu'un utilisateur clique sur un lien affilié puis effectue une réservation ou un achat auprès du site partenaire, 2DOLIST SAS peut percevoir une commission.</p><p>Sauf indication contraire, l'utilisation d'un lien affilié n'entraîne pas de coût supplémentaire facturé par Snow Explorer à l'utilisateur.</p><p>La transaction éventuelle est réalisée directement entre l'utilisateur et le site ou prestataire tiers concerné.</p><p>Snow Explorer n'est donc pas partie au contrat conclu entre l'utilisateur et ce prestataire lorsqu'aucune indication contraire n'est expressément mentionnée.</p><p>Les conditions de vente, d'annulation, de remboursement, de modification et de service après-vente applicables sont celles du prestataire auprès duquel la réservation ou l'achat est réalisé.</p></section>
    <section><h2>12. Classements et présentation des offres</h2><p>La présence, l'ordre ou la mise en avant d'une station, d'une offre, d'un prestataire ou d'un lien sur Snow Explorer peut dépendre de différents critères éditoriaux, techniques ou commerciaux.</p><p>Lorsqu'une mise en avant résulte d'un partenariat commercial ou d'une publicité et que cette nature commerciale n'est pas évidente, elle peut être identifiée comme telle.</p></section>
    <section><h2>13. Propriété intellectuelle</h2><p>Sauf mention contraire, la structure du Site, son organisation, les textes originaux, éléments graphiques et autres contenus créés spécifiquement pour Snow Explorer sont protégés par les règles applicables en matière de propriété intellectuelle.</p><p>Toute reproduction ou réutilisation substantielle de ces contenus sans autorisation préalable est interdite, sauf dans les cas autorisés par la loi.</p><p>Les marques, logos, photographies, cartes et autres contenus appartenant à des tiers restent la propriété de leurs titulaires respectifs.</p></section>
    <section><h2>14. Disponibilité du Site</h2><p>2DOLIST SAS s'efforce de maintenir le Site accessible mais ne garantit pas une disponibilité permanente ou sans interruption.</p><p>L'accès au Site peut notamment être interrompu pour des raisons de maintenance, de mise à jour, de problème technique ou pour toute autre raison indépendante de la volonté de 2DOLIST SAS.</p></section>
    <section><h2>15. Signalement d'une information incorrecte</h2><p>Malgré les vérifications réalisées, une information peut devenir obsolète ou comporter une erreur.</p><p>Tout utilisateur ou organisme concerné peut signaler une information incorrecte afin qu'elle puisse être vérifiée et, le cas échéant, corrigée.</p><p>Les modalités de contact de 2DOLIST SAS sont indiquées dans les <Link href="/mentions-legales">mentions légales</Link> du Site.</p></section>
    <section><h2>16. Données personnelles et cookies</h2><p>Le traitement éventuel de données personnelles et l'utilisation de cookies ou autres traceurs font l'objet des informations spécifiques accessibles dans la <Link href="/confidentialite">Politique de confidentialité</Link> et sur la page <Link href="/cookies">Cookies</Link>.</p><p>Lorsque la réglementation l'exige, le consentement de l'utilisateur est recueilli avant le dépôt ou la lecture de traceurs concernés.</p></section>
    <section><h2>17. Modification des CGU</h2><p>2DOLIST SAS peut modifier les présentes CGU afin de tenir compte notamment de l'évolution du Site, de ses fonctionnalités ou de la réglementation applicable.</p><p>La version applicable est celle accessible sur le Site à la date de consultation.</p></section>
    <section><h2>18. Droit applicable</h2><p>Les présentes CGU sont soumises au droit français.</p><p>En cas de difficulté concernant l'utilisation du Site, l'utilisateur peut contacter 2DOLIST SAS aux coordonnées figurant dans les <Link href="/mentions-legales">mentions légales</Link>.</p><p>Les règles légales impératives relatives à la juridiction compétente demeurent applicables.</p></section>
  </LegalPageLayout>;
}
