import LegalPageLayout from "@/components/legal/LegalPageLayout";
import Link from "next/link";

export default function ConfidentialitePage() {
  return <LegalPageLayout title="Politique de confidentialité" pageTitle="Politique de confidentialité | Snow Explorer" description="Informations sur le traitement des données personnelles sur Snow Explorer." canonicalPath="/confidentialite">
    <section><h2>Responsable du traitement</h2><p>Le responsable des traitements de données personnelles effectués dans le cadre de Snow Explorer est :</p><address className="legal-page__address">{`2DOLIST SAS
1735 route des Condamines
06670 Saint-Martin-du-Var
France`}</address><p>E-mail : <a href="mailto:support@2dolist.fr">support@2dolist.fr</a></p></section>
    <section><h2>Principe général</h2><p>Snow Explorer est principalement un service d'information accessible sans création obligatoire de compte.</p><p>2DOLIST SAS s'engage à limiter les données personnelles collectées à ce qui est nécessaire au fonctionnement du Site et aux finalités effectivement mises en œuvre.</p></section>
    <section><h2>Données pouvant être traitées</h2><p>Selon l'utilisation du Site, les catégories de données suivantes peuvent notamment être traitées.</p><h3>Données techniques</h3><p>Lors de l'accès au Site, certaines informations techniques peuvent être traitées automatiquement par les infrastructures nécessaires à son fonctionnement, telles que :</p><ul><li>adresse IP ;</li><li>date et heure de la requête ;</li><li>pages ou ressources demandées ;</li><li>informations techniques relatives au navigateur et à l'appareil ;</li><li>journaux techniques nécessaires à la sécurité, au diagnostic et au fonctionnement du service.</li></ul><h3>Données transmises volontairement</h3><p>Lorsqu'un utilisateur contacte Snow Explorer, les informations qu'il transmet volontairement peuvent être traitées afin de répondre à sa demande.</p><p>Il peut notamment s'agir de son adresse e-mail et du contenu de son message.</p><h3>Préférences relatives aux cookies</h3><p>Lorsque Snow Explorer utilise un mécanisme de gestion du consentement, le choix effectué par l'utilisateur concernant les cookies et traceurs peut être conservé afin de respecter sa décision.</p></section>
    <section><h2>Finalités</h2><p>Les données peuvent être traitées pour assurer le fonctionnement et la sécurité du Site, répondre aux demandes de contact et gérer les choix relatifs aux cookies.</p><p>Lorsque des outils facultatifs de mesure d'audience, de publicité ou d'autres traceurs sont effectivement utilisés et nécessitent le consentement, ils ne doivent être activés qu'après obtention de celui-ci.</p></section>
    <section><h2>Destinataires et sous-traitants</h2><p>Les données sont accessibles uniquement aux personnes et prestataires qui en ont besoin pour assurer le fonctionnement de Snow Explorer ou répondre aux demandes des utilisateurs.</p><p>L'infrastructure technique de Snow Explorer utilise notamment :</p><ul><li>Vercel Inc. pour l'hébergement et la diffusion de l'interface web ;</li><li>Render Services, Inc. pour l'hébergement de l'API et des services backend.</li></ul><p>D'autres prestataires ne doivent être mentionnés que s'ils sont réellement présents dans le projet.</p></section>
    <section><h2>Transferts hors de l'Union européenne</h2><p>Certains prestataires techniques utilisés par Snow Explorer sont établis aux États-Unis.</p><p>Lorsque des données personnelles font l'objet d'un transfert en dehors de l'Espace économique européen, 2DOLIST SAS veille à ce que ce transfert repose sur un mécanisme autorisé par la réglementation applicable.</p></section>
    <section><h2>Durées de conservation</h2><p>Les données sont conservées uniquement pendant la durée nécessaire à la finalité pour laquelle elles ont été collectées et au respect des obligations légales applicables.</p><p>Les données issues d'une demande adressée au support sont conservées pendant la durée nécessaire au traitement et au suivi de la demande, puis supprimées ou archivées lorsqu'elles ne sont plus nécessaires.</p><p>Les durées propres aux cookies et traceurs éventuellement utilisés sont précisées sur la page <Link href="/cookies">Cookies</Link> ou dans l'outil de gestion du consentement lorsqu'elles sont disponibles.</p></section>
    <section><h2>Droits des personnes</h2><p>Conformément à la réglementation applicable, une personne concernée peut, selon la situation, disposer notamment :</p><ul><li>d'un droit d'accès ;</li><li>d'un droit de rectification ;</li><li>d'un droit à l'effacement ;</li><li>d'un droit à la limitation ;</li><li>d'un droit d'opposition ;</li><li>d'un droit à la portabilité lorsque les conditions légales sont réunies ;</li><li>du droit de retirer son consentement à tout moment lorsque le traitement repose sur celui-ci.</li></ul><p>Pour exercer ces droits :</p><p><a href="mailto:support@2dolist.fr">support@2dolist.fr</a></p><p>La personne concernée peut également introduire une réclamation auprès de la Commission nationale de l'informatique et des libertés (CNIL).</p></section>
    <section><h2>Sécurité</h2><p>2DOLIST SAS met en œuvre des mesures techniques et organisationnelles destinées à protéger les données personnelles contre l'accès non autorisé, la perte, l'altération ou la divulgation non autorisée.</p><p>Aucun système informatique ne pouvant garantir un risque nul, ces mesures sont adaptées en fonction de la nature des données et des traitements mis en œuvre.</p></section>
    <section><h2>Modification de la politique</h2><p>La présente politique peut être modifiée afin de tenir compte de l'évolution de Snow Explorer, des services effectivement utilisés ou de la réglementation applicable.</p></section>
  </LegalPageLayout>;
}
