import LegalPageLayout from "@/components/legal/LegalPageLayout";

export default function CookiesPage() {
  return <LegalPageLayout title="Politique relative aux cookies" pageTitle="Cookies | Snow Explorer" description="Informations sur les cookies et traceurs susceptibles d'être utilisés sur Snow Explorer.">
    <section><h2>Qu'est-ce qu'un cookie ou un traceur ?</h2><p>Un cookie est un petit fichier ou une information pouvant être enregistré ou lu sur l'appareil d'un utilisateur lors de la consultation d'un site internet.</p><p>D'autres technologies peuvent avoir un fonctionnement comparable et sont également désignées dans cette politique sous le terme de « traceurs ».</p></section>
    <section><h2>Traceurs strictement nécessaires</h2><p>Snow Explorer peut utiliser des traceurs strictement nécessaires au fonctionnement du Site.</p><p>Ils peuvent notamment permettre :</p><ul><li>d'assurer la sécurité du Site ;</li><li>de conserver certains paramètres techniques ;</li><li>d'enregistrer les choix effectués concernant les cookies ;</li><li>de fournir une fonctionnalité expressément demandée par l'utilisateur.</li></ul><p>Lorsque les conditions prévues par la réglementation sont remplies, ces traceurs peuvent être utilisés sans consentement préalable.</p></section>
    <section><h2>Mesure d'audience</h2><p>Snow Explorer peut utiliser un service de mesure d'audience uniquement lorsqu'un tel service est effectivement installé sur le Site.</p><p>Lorsque le service ou sa configuration nécessite le consentement de l'utilisateur, il ne doit pas être chargé avant que ce consentement ait été obtenu.</p></section>
    <section><h2>Publicité et affiliation</h2><p>Snow Explorer peut comporter des publicités et des liens affiliés.</p><p>Un simple lien affilié n'implique pas nécessairement le dépôt d'un cookie sur Snow Explorer. En revanche, un partenaire ou une technologie publicitaire peut utiliser des traceurs lors du clic ou après redirection vers son propre service.</p><p>Lorsqu'un traceur soumis au consentement est déposé directement depuis Snow Explorer, il ne doit être activé qu'après acceptation de l'utilisateur.</p></section>
    <section><h2>Services tiers et contenus intégrés</h2><p>Certaines fonctionnalités peuvent provenir de services tiers, par exemple des cartes, contenus externes, lecteurs intégrés, données météorologiques ou autres widgets.</p><p>Un service tiers susceptible de déposer ou lire des traceurs soumis au consentement ne doit pas être chargé avant que l'utilisateur ait donné son accord lorsque celui-ci est légalement requis.</p></section>
    <section><h2>Choix de l'utilisateur</h2><p>Lorsqu'un gestionnaire de consentement est présent, l'utilisateur doit pouvoir :</p><ul><li>accepter les traceurs facultatifs ;</li><li>les refuser ;</li><li>effectuer un choix par catégorie lorsque cette possibilité est proposée ;</li><li>modifier ultérieurement son choix.</li></ul><p>Le refus des traceurs facultatifs ne doit pas empêcher l'accès aux fonctionnalités essentielles du Site.</p></section>
    <section><h2>Modifier ses préférences</h2><p>L'utilisateur peut modifier ses préférences à tout moment via la fonctionnalité de gestion des cookies accessible sur Snow Explorer lorsqu'elle est présente.</p><p>Le retrait du consentement doit être aussi simple que son octroi.</p></section>
    <section><h2>Liste des cookies et services</h2><p>À la date de la dernière mise à jour de cette page, aucun traceur facultatif nécessitant le consentement de l'utilisateur n'a été identifié dans le frontend Snow Explorer. Les services utilisés par le Site peuvent évoluer ; cette page sera mise à jour en conséquence.</p></section>
    <section><h2>Contact</h2><p><a href="mailto:support@2dolist.fr">support@2dolist.fr</a></p></section>
  </LegalPageLayout>;
}
