import Link from "next/link";
import { useRouter } from "next/router";
import { FormEvent, useCallback, useEffect, useState } from "react";
import ExpectationCard from "@/components/admin/catalog/ExpectationCard";
import { listCatalogExpectations, reconcileCatalog } from "@/lib/adminSkiAreaCatalogApi";
import type { CatalogExpectation, CatalogPagination, ExpectationState } from "@/types/skiAreaCatalog";
const initial:CatalogPagination={page:1,per_page:25,total:0,pages:0};
export default function ExpectationsPage(){
 const router=useRouter();
 const [items,setItems]=useState<CatalogExpectation[]>([]),[pagination,setPagination]=useState(initial),[page,setPage]=useState(1),[q,setQ]=useState(""),[search,setSearch]=useState(""),[state,setState]=useState<ExpectationState|"">("");const [queryReady,setQueryReady]=useState(false);const [loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 useEffect(()=>{if(!router.isReady||queryReady)return;const initialQ=typeof router.query.q==="string"?router.query.q:"";setQ(initialQ);setSearch(initialQ);setQueryReady(true)},[router.isReady,router.query.q,queryReady]);
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await listCatalogExpectations({page,q:search,state});setItems(data.items);setPagination(data.pagination)}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[page,search,state]);useEffect(()=>{void load()},[load]);
 const submit=(e:FormEvent)=>{e.preventDefault();setPage(1);setSearch(q)};const reconcile=async()=>{setError("");setNotice("");try{const r=await reconcileCatalog();setNotice(`${r.stations_scanned} station(s) analysée(s), ${r.proposals.length} proposition(s), aucune association automatique.`);await load()}catch(e){setError((e as Error).message)}};
 return <main className="admin-page"><header className="admin-page-heading"><div><p className="eyebrow">Domaines skiables</p><h1>Stations à rattacher</h1><p>{pagination.total} attente(s), dédupliquées par référence catalogue.</p></div><Link className="btn btn--secondary" href="/admin/domaines-skiables">Retour aux domaines</Link></header>
 <form className="catalog-toolbar" onSubmit={submit}><label>Recherche<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Nom ou station_ref"/></label><label>Statut<select value={state} onChange={e=>{setState(e.target.value as ExpectationState|"");setPage(1)}}><option value="">Tous les statuts</option><option value="pending">Stations manquantes</option><option value="needs_review">À vérifier</option><option value="optional_detail">Détails facultatifs</option><option value="ignored">Ignorées</option><option value="linked">Rattachées</option></select></label><button className="btn btn--secondary">Rechercher</button><button type="button" className="btn btn--primary" onClick={()=>void reconcile()}>Rechercher à nouveau</button></form>
 <p className="catalog-callout">Les alertes françaises manquantes et à vérifier sont distinguées des détails éditoriaux facultatifs. Utilisez les filtres pour isoler les entrées étrangères via leur pays.</p>{error&&<p className="admin-form-error" role="alert">{error}</p>}{notice&&<p className="admin-form-success" role="status">{notice}</p>}
 {loading?<p>Chargement des attentes…</p>:<div className="expectation-grid">{items.map(i=><ExpectationCard key={i.id} item={i} onChanged={()=>void load()}/>)}</div>}{!loading&&items.length===0&&<p className="empty-state">Aucune attente pour ces critères.</p>}
 <div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Précédent</button><span>Page {pagination.page}{pagination.pages?` sur ${pagination.pages}`:""}</span><button disabled={!pagination.pages||page>=pagination.pages} onClick={()=>setPage(v=>v+1)}>Suivant</button></div></main>}
