import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { getAdminSkiArea, listAdminSkiAreas, setAdminSkiAreaPublication } from "@/lib/adminSkiAreasApi";
import type { Pagination, SkiAreaAdmin } from "@/types/skiArea";
const initialPagination: Pagination = { page: 1, per_page: 20, total: 0, pages: 0 };
export default function AdminSkiAreas() {
 const [items,setItems]=useState<SkiAreaAdmin[]>([]),[pagination,setPagination]=useState(initialPagination),[counts,setCounts]=useState<Record<number,number>>({});
 const [q,setQ]=useState(""),[status,setStatus]=useState(""),[page,setPage]=useState(1),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const data=await listAdminSkiAreas({page,q,status});setItems(data.items);setPagination(data.pagination);const details=await Promise.allSettled(data.items.map(item=>getAdminSkiArea(item.id)));const next:Record<number,number>={};details.forEach((result,index)=>{if(result.status==="fulfilled")next[data.items[index].id]=result.value.ski_area.stations?.length||0;});setCounts(next);}catch(err){setError((err as Error).message);}finally{setLoading(false);}},[page,q,status]);
 useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer);},[load]);
 const publish=async(item:SkiAreaAdmin)=>{setError("");setNotice("");try{await setAdminSkiAreaPublication(item.id,item.status!=="published");setNotice(item.status==="published"?"Domaine dépublié.":"Domaine publié.");await load();}catch(err){setError((err as Error).message);}};
 return <main className="admin-page"><header className="admin-page-heading"><div><p className="eyebrow">Administration</p><h1>Domaines skiables</h1><p>{pagination.total} domaine(s)</p></div><Link className="btn btn--primary" href="/admin/domaines-skiables/new">Créer un domaine</Link></header>
 <section className="admin-list-filters"><label>Rechercher<input value={q} onChange={e=>{setQ(e.target.value);setPage(1);}} placeholder="Nom ou slug" /></label><label>Statut<select value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tous</option><option value="draft">Brouillons</option><option value="published">Publiés</option></select></label></section>
 {error&&<p className="admin-form-error" role="alert">{error}</p>}{notice&&<p className="admin-form-success" role="status">{notice}</p>}{loading?<p>Chargement des domaines…</p>:<div className="admin-table-wrap"><table className="admin-data-table"><thead><tr><th>Nom</th><th>Statut</th><th>Stations</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.name}</strong><small>{item.slug}</small></td><td><span className={`admin-status admin-status--${item.status}`}>{item.status==="published"?"Publié":"Brouillon"}</span></td><td>{counts[item.id]??"…"}</td><td><div className="admin-row-actions"><Link href={`/admin/domaines-skiables/${item.id}`}>Modifier</Link>{item.status==="published"&&<Link href={`/domaines-skiables/${item.slug}`}>Voir</Link>}<button type="button" onClick={()=>void publish(item)}>{item.status==="published"?"Dépublier":"Publier"}</button></div></td></tr>)}</tbody></table>{items.length===0&&<p className="empty-state">Aucun domaine trouvé.</p>}</div>}
 <div className="admin-pagination"><button disabled={page<=1} onClick={()=>setPage(v=>v-1)}>Précédent</button><span>Page {pagination.page}{pagination.pages?` sur ${pagination.pages}`:""}</span><button disabled={!pagination.pages||page>=pagination.pages} onClick={()=>setPage(v=>v+1)}>Suivant</button></div></main>;
}
