import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { getImportHistory } from "@/lib/api/stationImports";
import type { ImportHistoryFilters, ImportHistoryItem } from "@/types/stationImport";

export default function ImportHistoryPage() {
  const [filters, setFilters] = useState<ImportHistoryFilters>({}), [items, setItems] = useState<ImportHistoryItem[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const load = async (next = filters) => { setLoading(true); setError(""); try { setItems((await getImportHistory(next)).items); } catch (e) { setError(e instanceof Error ? e.message : "Historique indisponible."); } finally { setLoading(false); } };
  useEffect(() => { void load({}); }, []);
  const submit = (e: FormEvent) => { e.preventDefault(); void load(); };
  return <main className="admin-import-page"><div className="admin-import-heading"><div><p className="eyebrow">Administration</p><h1>Historique des imports</h1></div><Link className="btn btn--secondary" href="/admin/stations">Retour aux stations</Link></div><form className="history-filters" onSubmit={submit}><label>Date début<input type="date" value={filters.date_from || ""} onChange={e => setFilters(f => ({ ...f, date_from: e.target.value }))} /></label><label>Date fin<input type="date" value={filters.date_to || ""} onChange={e => setFilters(f => ({ ...f, date_to: e.target.value }))} /></label><label>Administrateur<input value={filters.administrator || ""} onChange={e => setFilters(f => ({ ...f, administrator: e.target.value }))} /></label><label>Statut<input value={filters.status || ""} onChange={e => setFilters(f => ({ ...f, status: e.target.value }))} /></label><label>Type<select value={filters.type || ""} onChange={e => setFilters(f => ({ ...f, type: e.target.value as ImportHistoryFilters["type"] || undefined }))}><option value="">Tous</option><option value="single">Simple</option><option value="bulk">Multiple</option></select></label><label>Station<input value={filters.station || ""} onChange={e => setFilters(f => ({ ...f, station: e.target.value }))} /></label><button className="btn btn--primary">Filtrer</button></form><div aria-live="polite">{loading && "Chargement de l’historique…"}{error && <div className="import-alert import-alert--error" role="alert">{error}</div>}</div>{!loading && !error && <div className="import-table-wrap"><table className="import-table"><thead><tr><th scope="col">Date</th><th scope="col">Administrateur</th><th scope="col">Type</th><th scope="col">Fichier</th><th scope="col">Statut</th><th scope="col">Analysées</th><th scope="col">Mises à jour</th><th scope="col">Créées</th><th scope="col">Ignorées</th><th scope="col">Erreurs</th><th scope="col">Action</th></tr></thead><tbody>{items.map(x => <tr key={x.id}><td>{new Date(x.created_at).toLocaleString("fr-FR")}</td><td>{x.administrator}</td><td>{x.type === "single" ? "Simple" : "Multiple"}</td><td>{x.filename}</td><td>{x.status}</td><td>{x.stations_analyzed}</td><td>{x.stations_updated}</td><td>{x.stations_created}</td><td>{x.stations_skipped}</td><td>{x.errors_count}</td><td><Link className="import-link" href={`/admin/imports/${x.id}`}>Voir le détail</Link></td></tr>)}</tbody></table>{items.length === 0 && <p className="import-empty">Aucun import trouvé.</p>}</div>}</main>;
}
